from __future__ import annotations

import json

import pytest

from ecoslice.receipt import receipt_block

from verify_gcode import diagnose, extract_receipt, main, read_ends

FOOTER = (
    "G28\nG1 X1 Y1 E1\n"
    "; filament used [g] = 12.85\n"
    "; estimated printing time (normal mode) = 34m 37s\n"
)

BASE_STATS = dict(
    mode="load-aware walls & infill",
    load_case="cube 8kg down, left wall",
    safety_factor=2.0,
    allowable_mpa=22.5,
    max_vm_mpa=24.8,
    solver="splu @ 3000 dof",
    voxels="32x32x32",
    reinforced_layers=2,
    relaxed_layers=2,
    added_grams=2.37,
    added_wall_grams=0.47,
    added_infill_grams=1.90,
    saved_vs_uniform_grams=9.95,
    co2e_saved_vs_uniform_g=57.3,
)


def _write(tmp_path, name: str, body: str):
    p = tmp_path / name
    p.write_text(body, encoding="utf-8")
    return p


def _sliced(**extra) -> str:
    """A G-code file as the plugin would actually write it."""
    return "; generated by OrcaSlicer\n" + receipt_block(dict(BASE_STATS, **extra)) + FOOTER


def test_no_markers_reads_as_not_run(tmp_path):
    p = _write(tmp_path, "a.gcode", "; generated by OrcaSlicer\nG28\n" + FOOTER)
    verdict, _ = diagnose(extract_receipt(p.read_text()), p.read_text())
    assert verdict == "no_marker"


def test_spike_marker_is_told_apart_from_the_plugin(tmp_path):
    body = ";ECOSLICE SPIKE touched this file\n; generated by OrcaSlicer\n" + FOOTER
    p = _write(tmp_path, "a.gcode", body)
    verdict, _ = diagnose(extract_receipt(body), body)
    assert verdict == "spike"
    assert p.exists()


def test_receipt_without_mutation_stats_is_analysis_only(tmp_path):
    body = _sliced()
    verdict, detail = diagnose(extract_receipt(body), body)
    assert verdict == "analysis_only"
    assert detail["planned"] == {"reinforced": 2, "relaxed": 2}


def test_zero_counts_are_a_no_op_not_a_success(tmp_path):
    """'ran and changed nothing' must never be reported as working."""
    body = _sliced(perimeters_added=0, perimeters_removed=0)
    verdict, detail = diagnose(extract_receipt(body), body)
    assert verdict == "no_op"
    assert detail["applied"] == {"reinforced": 0, "relaxed": 0}


def test_applied_mutations_read_as_success(tmp_path):
    body = _sliced(perimeters_added=84, perimeters_removed=12)
    verdict, detail = diagnose(extract_receipt(body), body)
    assert verdict == "ok"
    assert detail["applied"] == {"reinforced": 84, "relaxed": 12}
    assert detail["fields"]["max von Mises"] == "24.8 MPa"


def test_reinforcement_alone_counts_as_success(tmp_path):
    """Relaxation is a no-op on a stock profile, so it must not gate the verdict."""
    body = _sliced(perimeters_added=84, perimeters_removed=0)
    verdict, _ = diagnose(extract_receipt(body), body)
    assert verdict == "ok"


@pytest.mark.parametrize(
    "extra,code",
    [
        ({"perimeters_added": 84, "perimeters_removed": 12}, 0),
        ({"perimeters_added": 0, "perimeters_removed": 0}, 1),
        ({}, 1),
    ],
)
def test_exit_code_gates_on_a_real_change(tmp_path, capsys, extra, code):
    p = _write(tmp_path, "a.gcode", _sliced(**extra))
    assert main([str(p)]) == code


def test_missing_file_is_an_error_not_a_verdict(tmp_path, capsys):
    assert main([str(tmp_path / "nope.gcode")]) == 2


def test_json_output_carries_the_verdict_and_footer(tmp_path, capsys):
    p = _write(tmp_path, "a.gcode", _sliced(perimeters_added=84, perimeters_removed=12))
    main([str(p), "--json"])
    out = json.loads(capsys.readouterr().out)
    assert out["verdict"] == "ok" and out["ok"] is True
    assert out["applied"]["reinforced"] == 84
    assert out["footer"]["filament_g"] == pytest.approx(12.85)
    assert out["footer"]["print_time_s"] == pytest.approx(2077.0)


def test_large_file_is_not_read_whole(tmp_path):
    """G-code runs to hundreds of MB; the receipt is at the top and totals at the end."""
    filler = "G1 X1 Y1 E0.01\n" * 80_000
    body = "; generated by OrcaSlicer\n" + receipt_block(
        dict(BASE_STATS, perimeters_added=84, perimeters_removed=12)
    ) + filler + FOOTER
    p = _write(tmp_path, "big.gcode", body)
    assert p.stat().st_size > 1_000_000
    head, tail = read_ends(p)
    assert len(head) + len(tail) < p.stat().st_size
    verdict, _ = diagnose(extract_receipt(head), head)
    assert verdict == "ok"
    from ecoslice.receipt import parse_gcode_footer
    assert parse_gcode_footer(tail)["filament_g"] == pytest.approx(12.85)
