from __future__ import annotations

import pytest

from ecoslice.receipt import (
    format_duration,
    parse_duration_seconds,
    parse_gcode_footer,
    receipt_block,
)

FOOTER = """; generated by OrcaSlicer 2.5.0-dev
G1 X10 Y10 E1.2
; filament used [g] = 12.34
; filament used [cm3] = 9.95
; estimated printing time (normal mode) = 1h 54m 12s
; estimated printing time (silent mode) = 2h 10m 0s
"""


def test_parse_footer_reads_mass_volume_and_time():
    f = parse_gcode_footer(FOOTER)
    assert f["filament_g"] == pytest.approx(12.34)
    assert f["filament_cm3"] == pytest.approx(9.95)
    assert f["print_time_s"] == pytest.approx(6852.0)


def test_parse_footer_ignores_our_own_receipt_lines():
    """A re-export runs the post-processor over G-code that already has a receipt."""
    polluted = FOOTER + ";ECOSLICE measured mass   : 99.99 g\n"
    assert parse_gcode_footer(polluted)["filament_g"] == pytest.approx(12.34)


def test_parse_footer_returns_none_when_absent():
    f = parse_gcode_footer("G1 X0 Y0\nG1 X1 Y1\n")
    assert f == {"filament_g": None, "filament_cm3": None, "print_time_s": None}


@pytest.mark.parametrize(
    "text,seconds",
    [("40m", 2400.0), ("1h 54m 12s", 6852.0), ("2d 1h", 176400.0), ("45s", 45.0)],
)
def test_duration_parsing(text, seconds):
    assert parse_duration_seconds(text) == pytest.approx(seconds)


def test_duration_formatting():
    assert format_duration(6852.0) == "1h54m"
    assert format_duration(150.0) == "2m30s"
    assert format_duration(9.0) == "9s"


BASE_STATS = {
    "mode": "load-aware walls & infill",
    "load_case": "bracket",
    "safety_factor": 2.0,
    "allowable_mpa": 22.5,
    "max_vm_mpa": 24.8,
    "solver": "splu @ 3000 dof",
    "voxels": "40x4x4",
    "reinforced_layers": 2,
    "relaxed_layers": 2,
    "added_grams": 2.37,
    "added_wall_grams": 0.47,
    "added_infill_grams": 1.90,
    "saved_vs_uniform_grams": 9.95,
    "co2e_saved_vs_uniform_g": 57.3,
}


def test_receipt_splits_added_mass_into_walls_and_infill():
    block = receipt_block(BASE_STATS)
    assert "walls +0.47 g, solid infill +1.90 g" in block
    assert "+2.37 g localized" in block


def test_receipt_omits_measured_lines_when_the_footer_is_unavailable():
    block = receipt_block(BASE_STATS)
    assert "measured mass" not in block
    assert "measured time" not in block


def test_receipt_quotes_measured_mass_time_and_energy():
    stats = dict(BASE_STATS, measured_filament_g=12.34, measured_print_time_s=6852.0)
    block = receipt_block(stats)
    assert "measured mass   : 12.34 g" in block
    assert "measured time   : 1h54m" in block
    assert "0.190 kWh at 100 W" in block  # 1.9033 h * 100 W
    assert "model-vs-measured" in block


def test_receipt_labels_confidence_as_a_heuristic():
    stats = dict(BASE_STATS, confidence=0.6, confidence_label="moderate",
                 confidence_reasons="peak stress 1.10x allowable")
    block = receipt_block(stats)
    assert "confidence      : 0.60 (moderate)" in block
    assert "not a certification" in block
    assert "peak stress 1.10x allowable" in block
