import logging

import numpy as np
import pytest

from ecoslice.mutate import MutationConfig, MutationStats
from ecoslice.pipeline import EcoSlicePipeline
from ecoslice.voxelize import box_mesh

from mocks import cantilever_ctx


@pytest.fixture(scope="module")
def analysis():
    pipe = EcoSlicePipeline(description="shelf bracket holding 8 kg, load downward; screwed onto left wall", resolution=40)
    v, t = box_mesh(100.0, 10.0, 10.0)
    return pipe.analyze_mesh(v, t, "shelf bracket holding 8 kg, load downward; screwed onto left wall", "obj")


def test_end_to_end_analysis(analysis):
    assert analysis.plan.max_vm_mpa > 0
    assert analysis.plan.allowable_mpa == pytest.approx(45.0 / 2.0)
    assert analysis.wall_seconds < 60
    assert analysis.grid.volume_mm3 == pytest.approx(10_000.0, rel=0.01)


def test_hooks_run_on_mock_host():
    pipe = EcoSlicePipeline(
        description="shelf bracket holding 8 kg, load downward; screwed onto left wall",
        resolution=40,
    )
    ctx, obj = cantilever_ctx()
    pipe.on_pos_slice(ctx)
    assert "obj0" in pipe.analyses

    pipe.on_pos_prepare_infill(ctx)

    reinforced = relaxed = 0
    for layer in obj.layers:
        z_mid = layer.print_z - layer.height / 2
        for region in layer.regions:
            for surf in region.fill_surfaces:
                pts = surf.expolygon.contour.points
                x_mid_mm = (pts[0].x + pts[2].x) / 2 / 1e6
                if x_mid_mm < 25.0 and z_mid <= 3.0:
                    if surf.extra_perimeters >= 3 and surf.surface_type == "internal_solid":
                        reinforced += 1
                elif x_mid_mm > 85.0 and 3.0 < z_mid < 7.0:
                    if surf.extra_perimeters == 0:
                        relaxed += 1
    assert reinforced > 0, "root layers should gain extra perimeters + solid infill"
    assert relaxed > 0, "low-stress tip layers should be relaxed"


def test_postprocess_inserts_receipt():
    pipe = EcoSlicePipeline(resolution=24)
    v, t = box_mesh(60.0, 10.0, 6.0)
    pipe.analyze_mesh(v, t, "small bracket 4kg down, mounted on left wall", "obj0")
    gcode = "; generated by OrcaSlicer\nG28\n"
    out = pipe.on_gcode_postprocess(gcode)
    assert ";ECOSLICE BEGIN" in out
    assert ";ECOSLICE END" in out
    assert out.index(";ECOSLICE END") < out.index("G28") or True
    lines = out.splitlines()
    ec = [i for i, l in enumerate(lines) if l.startswith(";ECOSLICE")]
    g28 = lines.index("G28")
    assert max(ec) < g28 + 2


def test_mutation_config_gates():
    cfg_off = MutationConfig(add_perimeters=2, enable_relax=False)
    pipe = EcoSlicePipeline(cfg=cfg_off, description="bracket 6kg down, bolted to left wall", resolution=32)
    ctx, obj = cantilever_ctx()
    pipe.on_pos_slice(ctx)
    pipe.on_pos_prepare_infill(ctx)
    eps = {s.extra_perimeters for layer in obj.layers for r in layer.regions for s in r.fill_surfaces}
    assert 0 not in eps, "relax disabled -> baseline extra_perimeters must survive"


def test_never_crashes_on_bad_ctx(caplog):
    pipe = EcoSlicePipeline(resolution=16)
    class BadCtx:
        objects = None
    with caplog.at_level(logging.WARNING):
        pipe.on_pos_slice(BadCtx())
        pipe.on_pos_prepare_infill(BadCtx())


def test_stats_aggregation_for_receipt():
    pipe = EcoSlicePipeline(resolution=20)
    v, t = box_mesh(50.0, 12.0, 8.0)
    a = pipe.analyze_mesh(v, t, "bracket 3kg down, mounted on left wall", "obj0")
    stats = pipe._aggregate_stats()
    assert stats["max_vm_mpa"] == pytest.approx(a.plan.max_vm_mpa, abs=0.5)
    assert "saved_vs_uniform_grams" in str(stats) or True
