from pathlib import Path

import pytest

import sys

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "tools"))

import gcode_diff


BASELINE = """; generated by OrcaSlicer 2.4.2
; filament used [g] = 24.80
; filament used [cm3] = 20.00
; estimated printing time (normal mode) = 1h 21m 40s
M73
"""

OPTIMIZED = """; generated by OrcaSlicer 2.4.2
;ECOSLICE BEGIN
;ECOSLICE max von Mises   : 33.6 MPa
;ECOSLICE END
; filament used [g] = 22.96
; filament used [cm3] = 18.52
; estimated printing time (normal mode) = 1h 18m 2s
"""


def _write(tmp_path, name, text):
    p = tmp_path / name
    p.write_text(text, encoding="utf-8")
    return p


def test_parse(tmp_path):
    b = gcode_diff.parse_gcode(_write(tmp_path, "b.gcode", BASELINE))
    assert b["filament_g"] == pytest.approx(24.80)
    assert b["time_normal_s"] == pytest.approx(4900.0)


def test_compare(tmp_path):
    b = gcode_diff.parse_gcode(_write(tmp_path, "b.gcode", BASELINE))
    o = gcode_diff.parse_gcode(_write(tmp_path, "o.gcode", OPTIMIZED))
    cmp = gcode_diff.compare(b, o)
    assert cmp["delta_filament_g"] == pytest.approx(-1.84)
    assert cmp["delta_co2e_g_virgin_pla"] == pytest.approx(-10.60, abs=0.05)
    assert cmp["delta_time_normal_s"] == pytest.approx(-218.0)
    assert cmp["delta_energy_kwh_at_100w"] == pytest.approx(0.0061, abs=1e-3)


def test_assert_lighter_exit_code(tmp_path):
    b = _write(tmp_path, "b.gcode", BASELINE)
    o = _write(tmp_path, "o.gcode", OPTIMIZED)
    assert gcode_diff.main([str(b), str(o), "--assert-lighter"]) == 0
    assert gcode_diff.main([str(o), str(b), "--assert-lighter"]) == 1
