from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
PLUGIN = ROOT / "plugin" / "ecoslice_core.py"


@pytest.fixture(scope="module")
def bundled():
    assert PLUGIN.exists(), "run tools/build_plugin.py first"
    spec = importlib.util.spec_from_file_location("ecoslice_core_bundled", PLUGIN)
    mod = importlib.util.module_from_spec(spec)
    sys.modules["ecoslice_core_bundled"] = mod
    spec.loader.exec_module(mod)
    return mod


def test_header_and_metadata(bundled):
    text = PLUGIN.read_text(encoding="utf-8")
    assert text.startswith("# /// script")
    header = text.split("# ///")[1]
    assert 'requires-python = ">=3.12"' in text
    assert "numpy" in header and "scipy" in header
    d = bundled.describe()
    assert d["name"] == "EcoSlice"
    assert "SlicingPipeline" in d["capabilities"]
    assert "posPrepareInfill" in d["hooks"]


def test_bundled_pipeline_end_to_end(bundled):
    from ecoslice.voxelize import box_mesh

    pipe = bundled.create_pipeline(resolution=24)
    v, t = box_mesh(60.0, 10.0, 6.0)
    a = pipe.analyze_mesh(v, t, "bracket 4kg down; mounted left wall", "obj0")
    assert a.plan.max_vm_mpa > 0
    gcode = "; generated by OrcaSlicer\nG28\n"
    out = pipe.on_gcode_postprocess(gcode)
    assert ";ECOSLICE BEGIN" in out


def test_default_config_is_a_valid_dict(bundled):
    """The host requires get_default_config() to hand back an object, not a string."""
    import json

    cfg = bundled.DEFAULT_CONFIG
    assert isinstance(cfg, dict)
    assert isinstance(json.loads(json.dumps(cfg)), dict)
    assert "{{" not in PLUGIN.read_text(encoding="utf-8")


def test_config_round_trips_into_the_pipeline(bundled):
    import json

    pipe = bundled.create_pipeline()
    bundled._apply_config(pipe, json.dumps({"resolution": 24, "add_perimeters": 3}))
    assert pipe.resolution == 24
    assert pipe.cfg.add_perimeters == 3
    assert pipe.cfg.enable_relax is True

    bundled._apply_config(pipe, "not json at all")
    assert pipe.resolution == bundled.DEFAULT_CONFIG["resolution"]


def test_no_relative_imports_in_bundle(bundled):
    src = PLUGIN.read_text(encoding="utf-8")
    for i, line in enumerate(src.splitlines(), 1):
        if line.startswith("from .") or line.startswith("from ecoslice"):
            pytest.fail(f"intra-package import survived bundling at line {i}: {line}")
