# /// script
# requires-python = ">=3.12"
# dependencies = [
#   "numpy>=1.26",
#   "scipy>=1.11",
# ]
#
# [tool.orcaslicer.plugin]
# name = "EcoSlice"
# version = "0.1.0"
# description = "Load-aware walls & infill: FEM-driven localized reinforcement inside OrcaSlicer"
# author = "EcoSlice contributors"
# ///
# EcoSlice Core - load-aware walls & infill for OrcaSlicer.
# Copyright (C) 2026 EcoSlice contributors. License AGPL-3.0-or-later.
# This file is generated by tools/build_plugin.py - do not edit by hand.

from __future__ import annotations

import numpy as np
import inspect
import warnings
import scipy.sparse as sp
import json
import logging
import os
import re
import time
from dataclasses import dataclass, field
from scipy.sparse.linalg import LinearOperator, cg, splu
from typing import Optional


# ======================================================================
# module: __version__
# ======================================================================
__version__ = '0.1.0'

# ======================================================================
# module: voxelize
# ======================================================================
@dataclass(frozen=True)
class VoxelGrid:
    mask: np.ndarray
    origin: np.ndarray
    spacing: tuple[float, float, float]

    @property
    def shape(self) -> tuple[int, int, int]:
        return tuple(self.mask.shape)

    @property
    def h(self) -> float:
        return self.spacing[0]

    @property
    def volume_mm3(self) -> float:
        return float(self.mask.sum()) * self.h ** 3

    def cell_center(self, i: int, j: int, k: int) -> np.ndarray:
        return self.origin + (np.array([i, j, k], dtype=np.float64) + 0.5) * self.h

    def world_to_cell(self, pts_mm: np.ndarray) -> np.ndarray:
        pts = np.asarray(pts_mm, dtype=np.float64)
        return np.floor((pts - self.origin) / self.h).astype(np.int64)

def _triangle_hit_xs(tri2d: np.ndarray, tri_x: np.ndarray, p: np.ndarray) -> np.ndarray:
    a, b, c = (tri2d[:, 0], tri2d[:, 1], tri2d[:, 2])

    def cross(o, u, v):
        return (u[..., 0] - o[..., 0]) * (v[..., 1] - o[..., 1]) - (u[..., 1] - o[..., 1]) * (v[..., 0] - o[..., 0])
    area = cross(a, b, c)
    valid = np.abs(area) > 1e-12
    w0 = cross(a, b, p)
    w1 = cross(b, c, p)
    w2 = cross(c, a, p)
    inside = valid & ((w0 >= 0) & (w1 >= 0) & (w2 >= 0) | (w0 <= 0) & (w1 <= 0) & (w2 <= 0))
    if not inside.any():
        return np.empty(0, dtype=np.float64)
    lam0 = w1[inside] / area[inside]
    lam1 = w2[inside] / area[inside]
    lam2 = 1.0 - lam0 - lam1
    xa, xb, xc = (tri_x[:, 0], tri_x[:, 1], tri_x[:, 2])
    return lam0 * xa[inside] + lam1 * xb[inside] + lam2 * xc[inside]
MIN_CELLS_ACROSS_THINNEST = 4

def voxelize(vertices: np.ndarray, triangles: np.ndarray, resolution: int=32, min_cells_across: int=MIN_CELLS_ACROSS_THINNEST) -> VoxelGrid:
    """Solid voxelization by ray parity along +x.

    Cell size is driven by the longest axis, but never coarser than
    `min_cells_across` cells through the thinnest one: a plate or bracket with
    two elements through its thickness cannot represent bending at all.
    """
    v = np.asarray(vertices, dtype=np.float64)
    t = np.asarray(triangles, dtype=np.int64)
    if v.ndim != 2 or v.shape[1] != 3:
        raise ValueError('vertices must be (N,3)')
    if t.ndim != 2 or t.shape[1] != 3:
        raise ValueError('triangles must be (M,3)')
    mn, mx = (v.min(axis=0), v.max(axis=0))
    ext = np.maximum(mx - mn, 1e-09)
    h = float(ext.max()) / float(resolution)
    if min_cells_across > 0:
        h = min(h, float(ext.min()) / float(min_cells_across))
    n = np.maximum(np.ceil(ext / h).astype(np.int64), 1)
    tri = v[t]
    tri_yz = tri[:, :, 1:3]
    tri_x = tri[:, :, 0]
    cy = mn[1] + (np.arange(n[1]) + 0.5) * h
    cz = mn[2] + (np.arange(n[2]) + 0.5) * h
    cx_centers = mn[0] + (np.arange(n[0]) + 0.5) * h
    mask = np.zeros(tuple((int(x) for x in n)), dtype=bool)
    tol = max(1e-09, h * 1e-09)
    for j, y in enumerate(cy):
        for k, z in enumerate(cz):
            xs = _triangle_hit_xs(tri_yz, tri_x, np.array([y, z]))
            if xs.size < 2:
                continue
            xs.sort()
            merged = []
            for x in xs:
                if not merged or x - merged[-1] > tol:
                    merged.append(x)
            xs = np.asarray(merged)
            if xs.size < 2:
                continue
            for a in range(0, xs.size - 1, 2):
                lo, hi = (xs[a], xs[a + 1])
                if hi - lo <= tol:
                    continue
                i0 = int(np.searchsorted(cx_centers, lo, side='right'))
                i1 = int(np.searchsorted(cx_centers, hi, side='left'))
                if i1 > i0:
                    mask[i0:i1, j, k] = True
    return VoxelGrid(mask=mask, origin=mn.copy(), spacing=(h, h, h))

def boundary_voxels(grid: VoxelGrid) -> np.ndarray:
    m = grid.mask
    interior = np.zeros_like(m)
    interior[1:-1, 1:-1, 1:-1] = m[1:-1, 1:-1, 1:-1] & m[:-2, 1:-1, 1:-1] & m[2:, 1:-1, 1:-1] & m[1:-1, :-2, 1:-1] & m[1:-1, 2:, 1:-1] & m[1:-1, 1:-1, :-2] & m[1:-1, 1:-1, 2:]
    return m & ~interior

def box_mesh(lx: float, ly: float, lz: float, ox: float=0.0, oy: float=0.0, oz: float=0.0):
    corners = np.array([[ox, oy, oz], [ox + lx, oy, oz], [ox + lx, oy + ly, oz], [ox, oy + ly, oz], [ox, oy, oz + lz], [ox + lx, oy, oz + lz], [ox + lx, oy + ly, oz + lz], [ox, oy + ly, oz + lz]], dtype=np.float64)
    quads = [(0, 3, 2, 1), (4, 5, 6, 7), (0, 1, 5, 4), (1, 2, 6, 5), (2, 3, 7, 6), (3, 0, 4, 7)]
    tris = []
    for a, b, c, d in quads:
        tris.append((a, b, c))
        tris.append((a, c, d))
    return (corners, np.array(tris, dtype=np.int32))

def uv_sphere_mesh(radius: float, segments: int=24, rings: int=12, center=(0.0, 0.0, 0.0)):
    lat = np.linspace(-np.pi / 2, np.pi / 2, rings + 2)[1:-1]
    lon = np.linspace(0, 2 * np.pi, segments, endpoint=False)
    verts = [np.array([0.0, 0.0, radius])]
    for phi in lat:
        for theta in lon:
            verts.append(np.array([radius * np.cos(phi) * np.cos(theta), radius * np.cos(phi) * np.sin(theta), radius * np.sin(phi)]))
    south = np.array([0.0, 0.0, -radius])
    verts.append(south)
    v = np.array(verts) + np.asarray(center)
    tris = []
    top_ring = 1 + np.arange(segments)
    for s in range(segments):
        tris.append((0, top_ring[s], top_ring[(s + 1) % segments]))
    for r in range(rings - 1):
        base = 1 + r * segments
        nxt = base + segments
        for s in range(segments):
            s2 = (s + 1) % segments
            tris.append((base + s, nxt + s, nxt + s2))
            tris.append((base + s, nxt + s2, base + s2))
    last = len(v) - 1
    base_last = 1 + (rings - 1) * segments
    for s in range(segments):
        s2 = (s + 1) % segments
        tris.append((last, base_last + s2, base_last + s))
    return (v, np.array(tris, dtype=np.int32))

# ======================================================================
# module: fem
# ======================================================================
try:
    import pyamg
    HAS_PYAMG = True
except ImportError:
    HAS_PYAMG = False
_CG_TOL_KW = 'rtol' if 'rtol' in inspect.signature(cg).parameters else 'tol'
NODE_ORDER = [(dx, dy, dz) for dz in (0, 1) for dy in (0, 1) for dx in (0, 1)]
FACES = {'x+': 0, 'x-': 0, 'y+': 1, 'y-': 1, 'z+': 2, 'z-': 2}
FACE_ALIASES = {'right': 'x+', 'left': 'x-', 'back': 'y+', 'front': 'y-', 'top': 'z+', 'bottom': 'z-'}
DIRECT_SOLVE_MAX_DOF = 8000
CG_MAX_ITER = 5000
CG_RTOL = 1e-08

def canonical_face(face: str) -> str:
    f = FACE_ALIASES.get(str(face).strip().lower(), str(face).strip().lower())
    if f not in FACES:
        raise ValueError(f'unknown face {face!r}; expected one of {sorted(FACES)} or {sorted(FACE_ALIASES)}')
    return f

def opposite_face(face: str) -> str:
    f = canonical_face(face)
    return f[0] + ('-' if f.endswith('+') else '+')

def _isotropic_D(E: float, nu: float) -> np.ndarray:
    lam = E * nu / ((1.0 + nu) * (1.0 - 2.0 * nu))
    mu = E / (2.0 * (1.0 + nu))
    D = np.zeros((6, 6))
    D[0, 0] = D[1, 1] = D[2, 2] = lam + 2.0 * mu
    D[0, 1] = D[0, 2] = D[1, 0] = D[1, 2] = D[2, 0] = D[2, 1] = lam
    D[3, 3] = D[4, 4] = D[5, 5] = mu
    return D

def _hex8_ke(h: float, E: float, nu: float) -> tuple[np.ndarray, list[np.ndarray]]:
    g = 1.0 / np.sqrt(3.0)
    D = _isotropic_D(E, nu)
    Ke = np.zeros((24, 24))
    B_list = []
    for xi in (-g, g):
        for eta in (-g, g):
            for zeta in (-g, g):
                dN_dg = np.empty((3, 8))
                for a, (dx, dy, dz) in enumerate(NODE_ORDER):
                    sx, sy, sz = (dx * 2 - 1, dy * 2 - 1, dz * 2 - 1)
                    dN_dg[0, a] = 0.125 * sx * (1 + sy * eta) * (1 + sz * zeta)
                    dN_dg[1, a] = 0.125 * sy * (1 + sx * xi) * (1 + sz * zeta)
                    dN_dg[2, a] = 0.125 * sz * (1 + sx * xi) * (1 + sy * eta)
                J = np.eye(3) * (h / 2.0)
                detJ = (h / 2.0) ** 3
                dN_dx = np.linalg.solve(J, dN_dg)
                B = np.zeros((6, 24))
                for a in range(8):
                    bx, by, bz = dN_dx[:, a]
                    o = 3 * a
                    B[0, o + 0] = bx
                    B[1, o + 1] = by
                    B[2, o + 2] = bz
                    B[3, o + 0] = by
                    B[3, o + 1] = bx
                    B[4, o + 1] = bz
                    B[4, o + 2] = by
                    B[5, o + 0] = bz
                    B[5, o + 2] = bx
                Ke += B.T @ D @ B * detJ
                B_list.append(B)
    return (Ke, B_list)

@dataclass
class FemResult:
    von_mises: np.ndarray
    max_displacement_mm: float
    solver: str
    face_displacement: dict = field(default_factory=dict)
    n_dof: int = 0
    iterations: int = 0

def _face_nodes(grid, node_grid_shape, face: str, avoid_faces=(), patch: str='full'):
    f = canonical_face(face)
    axis = FACES[f]
    n = node_grid_shape
    idx = [np.arange(n[i]) for i in range(3)]
    grids = np.meshgrid(*idx, indexing='ij')
    sel = [grids[i].ravel() for i in range(3)]
    keep = sel[axis] == (n[axis] - 1 if f.endswith('+') else 0)
    nodes = np.stack([s[keep] for s in sel], axis=1)
    if patch == 'far' and nodes.shape[0] > 1:
        for af in avoid_faces:
            try:
                a = canonical_face(af)
            except ValueError:
                continue
            ax = FACES[a]
            if ax == axis:
                continue
            hi = a.endswith('+')
            coord = nodes[:, ax]
            if hi:
                far = coord <= coord.max() - 0.5 * (coord.max() - coord.min()) - 1e-09
            else:
                far = coord >= coord.min() + 0.5 * (coord.max() - coord.min()) + 1e-09
            if far.any():
                nodes = nodes[far]
    return nodes

def _active_positions(active_nodes: np.ndarray, flat_ids: np.ndarray) -> np.ndarray:
    if active_nodes.size == 0 or flat_ids.size == 0:
        return np.empty(0, dtype=np.int64)
    pos = np.clip(np.searchsorted(active_nodes, flat_ids), 0, active_nodes.size - 1)
    return pos[active_nodes[pos] == flat_ids]

def _assemble_free(dof_map: np.ndarray, Ke: np.ndarray, free_index: np.ndarray, n_free: int):
    rows, cols, vals = ([], [], [])
    ke_flat = Ke.ravel()
    ne = dof_map.shape[0]
    chunk = 4096
    for s in range(0, ne, chunk):
        dm = free_index[dof_map[s:s + chunk]]
        m = dm.shape[0]
        r = np.repeat(dm, 24, axis=1).ravel()
        c = np.tile(dm, (1, 24)).ravel()
        keep = (r >= 0) & (c >= 0)
        if not keep.any():
            continue
        rows.append(r[keep].astype(np.int32))
        cols.append(c[keep].astype(np.int32))
        vals.append(np.tile(ke_flat, m)[keep])
    if not rows:
        raise ValueError('no free degrees of freedom left after applying constraints')
    return sp.coo_matrix((np.concatenate(vals), (np.concatenate(rows), np.concatenate(cols))), shape=(n_free, n_free)).tocsr()

def _solve_linear_system(K: sp.spmatrix, f: np.ndarray) -> tuple[np.ndarray, str, int]:
    n = f.size
    if n <= DIRECT_SOLVE_MAX_DOF:
        return (splu(K.tocsc()).solve(f), 'splu', 0)
    diag = K.diagonal()
    diag = np.where(np.abs(diag) > 0, diag, 1.0)
    jacobi = LinearOperator(K.shape, matvec=lambda x: x / diag)
    iters = 0

    def _count(_xk):
        nonlocal iters
        iters += 1
    u, info = cg(K, f, M=jacobi, maxiter=CG_MAX_ITER, callback=_count, **{_CG_TOL_KW: CG_RTOL})
    if info == 0:
        return (u, f'jacobi-cg({iters}it)', iters)
    if HAS_PYAMG:
        try:
            ml = pyamg.smoothed_aggregation_solver(K)
            residuals: list[float] = []
            u = ml.solve(f, tol=CG_RTOL, accel='cg', residuals=residuals)
            return (u, f'pyamg-cg({len(ml.levels)}lv,{max(len(residuals) - 1, 0)}it)', len(residuals))
        except Exception as exc:
            warnings.warn(f'pyamg path failed ({exc}); falling back to direct solve')
    warnings.warn(f'CG did not converge (info={info}); falling back to direct solve — this may be slow')
    return (splu(K.tocsc()).solve(f), 'splu-fallback', iters)

def solve_voxel_fem(grid, fixed_faces, load_face, load_vector_n, young_modulus_mpa: float=2400.0, poisson: float=0.3, load_patch: str='far'):
    mask = grid.mask
    nx, ny, nz = mask.shape
    h = grid.h
    elems = np.argwhere(mask)
    ne = elems.shape[0]
    if ne == 0:
        raise ValueError('empty voxel grid')
    node_grid = (nx + 1, ny + 1, nz + 1)
    nid = np.arange(node_grid[0] * node_grid[1] * node_grid[2]).reshape(node_grid)
    conn_global = np.empty((ne, 8), dtype=np.int64)
    for a, (dx, dy, dz) in enumerate(NODE_ORDER):
        conn_global[:, a] = nid[elems[:, 0] + dx, elems[:, 1] + dy, elems[:, 2] + dz]
    active_nodes, active_inv = np.unique(conn_global, return_inverse=True)
    conn_local = active_inv.reshape(ne, 8)
    n_active = active_nodes.shape[0]
    ndof_full = n_active * 3
    dof_map = ((conn_local * 3)[:, :, None] + np.arange(3)[None, None, :]).reshape(ne, 24)
    fixed_mask = np.zeros(n_active, dtype=bool)
    for face in fixed_faces:
        fn = _face_nodes(grid, node_grid, face)
        flat = nid[fn[:, 0], fn[:, 1], fn[:, 2]]
        fixed_mask[_active_positions(active_nodes, flat)] = True
    if not fixed_mask.any():
        raise ValueError(f'constraint faces {list(fixed_faces)} touch no material — the part is unsupported')
    ln = _face_nodes(grid, node_grid, load_face, avoid_faces=fixed_faces, patch=load_patch)
    lflat = nid[ln[:, 0], ln[:, 1], ln[:, 2]]
    lpos = _active_positions(active_nodes, lflat)
    if lpos.size == 0:
        raise ValueError(f'load face {load_face!r} touches no material')
    if fixed_mask[lpos].all():
        raise ValueError(f'load face {load_face!r} is fully constrained by {list(fixed_faces)} — the load would be carried straight into the fixture (no stress to solve for)')
    free = np.flatnonzero(~fixed_mask)
    free_dofs = (free[:, None] * 3 + np.arange(3)).ravel()
    free_index = np.full(ndof_full, -1, dtype=np.int64)
    free_index[free_dofs] = np.arange(free_dofs.size)
    force_full = np.zeros((n_active, 3))
    force_full[lpos] = np.asarray(load_vector_n, dtype=np.float64) / lpos.size
    f_free = force_full.reshape(-1)[free_dofs]
    Ke, B_list = _hex8_ke(h, young_modulus_mpa, poisson)
    K = _assemble_free(dof_map, Ke, free_index, free_dofs.size)
    u_f, used_solver, iters = _solve_linear_system(K, f_free)
    u_full = np.zeros(ndof_full)
    u_full[free_dofs] = u_f
    D = _isotropic_D(young_modulus_mpa, poisson)
    vm = np.zeros(ne)
    u_e = u_full[dof_map]
    for B in B_list:
        eps = np.einsum('ij,ej->ei', B, u_e)
        sig = eps @ D.T
        sx, sy, sz, txy, tyz, txz = (sig[:, 0], sig[:, 1], sig[:, 2], sig[:, 3], sig[:, 4], sig[:, 5])
        vm += 0.5 * ((sx - sy) ** 2 + (sy - sz) ** 2 + (sz - sx) ** 2) + 3.0 * (txy ** 2 + tyz ** 2 + txz ** 2)
    vm = np.sqrt(vm / len(B_list))
    vm_grid = np.zeros(mask.shape)
    vm_grid[elems[:, 0], elems[:, 1], elems[:, 2]] = vm
    u_vec = u_full.reshape(-1, 3)
    dirn = np.asarray(load_vector_n, dtype=np.float64)
    norm = np.linalg.norm(dirn)
    dirn = dirn / norm if norm > 0 else np.array([0.0, 0.0, -1.0])
    disp_out = {canonical_face(load_face): float(np.mean(u_vec[lpos] @ dirn))}
    return FemResult(von_mises=vm_grid, max_displacement_mm=float(np.abs(u_vec).max()), solver=used_solver, face_displacement=disp_out, n_dof=int(free_dofs.size), iterations=iters)

def cantilever_reference(L: float, b: float, hh: float, P: float, E: float) -> tuple[float, float]:
    I = b * hh ** 3 / 12.0
    delta = P * L ** 3 / (3.0 * E * I)
    sigma = P * L * (hh / 2.0) / I
    return (delta, sigma)

# ======================================================================
# module: loadcase
# ======================================================================
log = logging.getLogger('ecoslice.loadcase')

@dataclass
class Force:
    direction: tuple[float, float, float]
    magnitude_n: float
    face: str

    def normalized(self) -> np.ndarray:
        return np_normalize(self.direction)

@dataclass
class Constraint:
    face: str

@dataclass
class LoadCase:
    description: str = ''
    forces: list[Force] = field(default_factory=list)
    constraints: list[Constraint] = field(default_factory=list)
    safety_factor: float = 2.0
    young_modulus_mpa: float = 2400.0
    poisson: float = 0.36
    yield_mpa: float = 45.0
    source: str = 'heuristic'

    def to_json(self) -> str:
        return json.dumps({'description': self.description, 'forces': [{'direction': list(f.direction), 'magnitude_n': f.magnitude_n, 'face': f.face} for f in self.forces], 'constraints': [{'face': c.face} for c in self.constraints], 'safety_factor': self.safety_factor, 'young_modulus_mpa': self.young_modulus_mpa, 'poisson': self.poisson, 'yield_mpa': self.yield_mpa, 'source': self.source}, indent=2)

    @staticmethod
    def from_json(text: str) -> 'LoadCase':
        raw = json.loads(_strip_code_fence(text))
        return LoadCase.from_dict(raw)

    @staticmethod
    def from_dict(raw: dict) -> 'LoadCase':
        lc = LoadCase(description=str(raw.get('description', '')))
        for f in raw.get('forces', []):
            d = f.get('direction') or f.get('dir')
            if not d or len(d) != 3:
                raise ValueError('force needs direction of 3 components')
            mag = float(f.get('magnitude_n', f.get('magnitude_N', 0)))
            face = f.get('face', _dominant_face(d))
            lc.forces.append(Force(direction=(float(d[0]), float(d[1]), float(d[2])), magnitude_n=mag, face=str(face)))
        for c in raw.get('constraints', []):
            face = c.get('face') if isinstance(c, dict) else str(c)
            lc.constraints.append(Constraint(face=str(face)))
        lc.safety_factor = float(raw.get('safety_factor', 2.0))
        lc.young_modulus_mpa = float(raw.get('young_modulus_mpa', 2400.0))
        lc.poisson = float(raw.get('poisson', 0.36))
        lc.yield_mpa = float(raw.get('yield_mpa', 45.0))
        lc.source = str(raw.get('source', 'llm'))
        lc.validate()
        return lc

    def validate(self) -> None:
        if not self.constraints:
            raise ValueError('load case needs at least one constraint (how is the part held?)')
        if not self.forces:
            raise ValueError('load case needs at least one force')
        for f in self.forces:
            if f.magnitude_n <= 0:
                raise ValueError('force magnitude must be > 0')
        if not 1.0 <= self.safety_factor <= 10.0:
            raise ValueError('safety_factor out of range [1,10]')

def np_normalize(v):
    a = np.asarray(v, dtype=np.float64)
    n = np.linalg.norm(a)
    if n < 1e-12:
        return np.array([0.0, 0.0, -1.0])
    return a / n

def _dominant_face(direction) -> str:
    d = np_normalize(direction)
    axis = int(np.argmax(np.abs(d)))
    return ['x', 'y', 'z'][axis] + ('+' if d[axis] >= 0 else '-')

def _strip_code_fence(text: str) -> str:
    t = text.strip()
    if t.startswith('```'):
        t = re.sub('^```[a-zA-Z]*\\n?', '', t)
        t = re.sub('\\n?```\\s*$', '', t)
    i, j = (t.find('{'), t.rfind('}'))
    if i != -1 and j != -1:
        t = t[i:j + 1]
    return t
_MASS_RE = re.compile('(\\d+(?:[.,]\\d+)?)\\s*(kg|kgs|kilogram|kilograms|g|gram|grams|lb|lbs|pound|pounds|n|newton|newtons)\\b', re.IGNORECASE)
_SF_RE = re.compile('safety\\s*factor\\s*(?:of|:)?\\s*(\\d+(?:\\.\\d+)?)', re.IGNORECASE)
_DIR_WORDS = {'down': (0.0, 0.0, -1.0), 'downward': (0.0, 0.0, -1.0), 'downwards': (0.0, 0.0, -1.0), 'up': (0.0, 0.0, 1.0), 'upward': (0.0, 0.0, 1.0), 'left': (-1.0, 0.0, 0.0), 'right': (1.0, 0.0, 0.0), 'front': (0.0, -1.0, 0.0), 'forward': (0.0, -1.0, 0.0), 'back': (0.0, 1.0, 0.0), 'backward': (0.0, 1.0, 0.0)}
_ATTACH_RE = re.compile('(screw|bolt|mount|attach|clamp|fix|anchor|fasten)\\w*', re.IGNORECASE)
_FACE_PATTERNS = [(re.compile('\\bleft\\b', re.I), 'x-'), (re.compile('\\bright\\b', re.I), 'x+'), (re.compile('\\bback\\b', re.I), 'y+'), (re.compile('\\brear\\b', re.I), 'y+'), (re.compile('\\bfront\\b', re.I), 'y-'), (re.compile('\\bbottom\\b|\\bbase\\b|\\bfloor\\b|\\bdesk\\b', re.I), 'z-'), (re.compile('\\btop\\b|\\bceiling\\b', re.I), 'z+')]

def _to_newtons(value: float, unit: str) -> float:
    u = unit.lower()
    if u.startswith(('kg', 'kilo')):
        return value * 9.80665
    if u == 'g' or u.startswith('gram'):
        return value * 0.00980665
    if u.startswith('lb') or u.startswith('pound'):
        return value * 4.44822
    return value

def parse_description(text: str) -> LoadCase:
    desc = text.strip()
    forces: list[Force] = []
    constraints: dict[str, Constraint] = {}
    m_attach = _ATTACH_RE.search(desc)
    tail = desc[m_attach.start():] if m_attach else desc
    for pat, face in _FACE_PATTERNS:
        if pat.search(tail):
            constraints.setdefault(face, Constraint(face=face))
    segs = [s for s in re.split('[;\\n]|\\band then\\b', desc) if s.strip()]
    pool = segs if len(segs) > 1 else [desc]
    for seg in pool:
        m = _MASS_RE.search(seg)
        if not m:
            continue
        mag = _to_newtons(float(m.group(1).replace(',', '.')), m.group(2))
        direction = None
        for w, v in _DIR_WORDS.items():
            if re.search(f'\\b{w}\\b', seg, re.IGNORECASE):
                direction = v
                break
        if direction is None:
            after = seg[m.end():]
            for w, v in _DIR_WORDS.items():
                if re.search(f'\\b{w}\\b', after, re.IGNORECASE):
                    direction = v
                    break
        if direction is None:
            direction = (0.0, 0.0, -1.0)
        face = _dominant_face(direction)
        forces.append(Force(direction=direction, magnitude_n=round(mag, 3), face=face))
    sf_match = _SF_RE.search(desc)
    sf = float(sf_match.group(1)) if sf_match else 2.0
    mat = {}
    m_e = re.search('(\\d{3,5})\\s*mpa[^\\n]{0,20}?modul|modulus[^\\n]{0,20}?(\\d{3,5})\\s*mpa', desc, re.IGNORECASE)
    if m_e:
        mat['young_modulus_mpa'] = float(m_e.group(1) or m_e.group(2))
    m_y = re.search('yield[^\\d]{0,15}(\\d{2,3})\\s*mpa', desc, re.IGNORECASE)
    if m_y:
        mat['yield_mpa'] = float(m_y.group(1))
    if not constraints:
        constraints['z-'] = Constraint(face='z-')
    if not forces:
        forces.append(Force(direction=(0.0, 0.0, -1.0), magnitude_n=20.0, face='z-'))
    lc = LoadCase(description=desc, forces=forces, constraints=list(constraints.values()), safety_factor=sf, source='heuristic', **mat)
    lc.validate()
    return lc
_LLM_PROMPT = 'You convert natural-language descriptions of a mechanical part\'s job into a strict JSON load case for FEA.\n\nSchema:\n{\n  "description": string,\n  "forces": [{"direction": [x,y,z] unit-ish vector, "magnitude_n": number>0, "face": one of "x+","x-","y+","y-","z+","z-"}],\n  "constraints": [{"face": same enum}],\n  "safety_factor": number in [1,10],\n  "young_modulus_mpa": number, "poisson": number, "yield_mpa": number\n}\nFrame: x right, y back (depth), z up. Gravity pulls -z.\nConvert masses to newtons (kg -> *9.81). Faces describe where loads attach / where the part is held.\n\nPart description:\n'
DEFAULT_MODEL = 'claude-opus-5'

def llm_parse_description(text: str, model: str | None=None) -> Optional[LoadCase]:
    """Structured load case via the Messages API.

    Raw HTTP on purpose: the plugin runs inside OrcaSlicer's embedded interpreter,
    where every PEP 723 dependency is installed by the host at load time, so the
    Anthropic SDK is not available and stdlib urllib is the only transport.
    Any failure returns None and the deterministic parser takes over.
    """
    api_key = os.environ.get('ANTHROPIC_API_KEY')
    if not api_key:
        return None
    model = model or os.environ.get('ECOSLICE_MODEL') or DEFAULT_MODEL
    try:
        import urllib.request
        body = json.dumps({'model': model, 'max_tokens': 2048, 'output_config': {'effort': 'low'}, 'messages': [{'role': 'user', 'content': _LLM_PROMPT + text}]}).encode()
        req = urllib.request.Request('https://api.anthropic.com/v1/messages', data=body, headers={'content-type': 'application/json', 'x-api-key': api_key, 'anthropic-version': '2023-06-01'})
        with urllib.request.urlopen(req, timeout=30) as resp:
            data = json.loads(resp.read())
        if data.get('stop_reason') == 'refusal':
            log.warning('load-case extraction refused by the model; using the heuristic parser')
            return None
        content = ''.join((b.get('text', '') for b in data.get('content', []) if b.get('type') == 'text'))
        lc = LoadCase.from_json(content)
        lc.description = text.strip()
        lc.source = f'llm:{model}'
        return lc
    except Exception as exc:
        log.info('LLM load-case extraction unavailable (%s); using the heuristic parser', exc)
        return None

def extract_load_case(text: str, prefer_llm: bool=True) -> LoadCase:
    if prefer_llm:
        lc = llm_parse_description(text)
        if lc is not None:
            return lc
    return parse_description(text)

# ======================================================================
# module: mapping
# ======================================================================
@dataclass
class LayerAction:
    z0_mm: float
    z1_mm: float
    reinforce_xy: np.ndarray
    relax_xy: np.ndarray
    mean_utilization: float
    p95_utilization: float
    n_voxels: int
    median_utilization: float = 0.0
    occupied_xy: np.ndarray | None = None

@dataclass
class Plan:
    actions: list[LayerAction] = field(default_factory=list)
    allowable_mpa: float = 0.0
    max_vm_mpa: float = 0.0
    global_mean_utilization: float = 0.0
    n_reinforced_layers: int = 0
    n_relaxed_layers: int = 0
    solver: str = ''
    max_displacement_mm: float = 0.0

    @property
    def has_work(self) -> bool:
        return self.n_reinforced_layers > 0 or self.n_relaxed_layers > 0

def plan_from_stress(grid, von_mises: np.ndarray, *, yield_mpa: float, safety_factor: float, layer_height_mm: float | None=None, reinforce_frac: float=0.6, hotspot_frac: float=1.0, relax_frac: float=0.2, min_reinforce_columns_per_layer: int=2) -> Plan:
    mask = grid.mask
    h = grid.h
    allowable = yield_mpa / safety_factor
    util = np.zeros_like(von_mises)
    occ = mask & (von_mises > 0)
    util[occ] = von_mises[occ] / allowable
    if layer_height_mm is None or layer_height_mm <= 0:
        voxels_per_band = 1
    else:
        voxels_per_band = max(1, int(round(layer_height_mm / h)))
    nz = mask.shape[2]
    plan = Plan(allowable_mpa=allowable, max_vm_mpa=float(von_mises.max()))
    k = 0
    while k < nz:
        k_end = min(k + voxels_per_band, nz)
        band = occ[:, :, k:k_end]
        uband = util[:, :, k:k_end]
        n_vox = int(band.sum())
        if n_vox == 0:
            k = k_end
            continue
        vals = uband[band]
        mean_u = float(vals.mean())
        med_u = float(np.median(vals))
        p95_u = float(np.percentile(vals, 95))
        col_hot = (uband >= reinforce_frac).any(axis=2)
        col_cold = (uband <= relax_frac).all(axis=2)
        col_occupied = band.any(axis=2)
        hot_count = int(col_hot.sum())
        if mean_u >= reinforce_frac or (p95_u >= hotspot_frac and hot_count >= min_reinforce_columns_per_layer):
            reinforce = col_hot
            relax = np.zeros_like(col_hot)
        elif med_u <= relax_frac and (not col_hot.any()):
            reinforce = np.zeros_like(col_hot)
            relax = col_cold
        else:
            reinforce = np.zeros_like(col_hot)
            relax = np.zeros_like(col_hot)
        z0 = grid.origin[2] + k * h
        z1 = grid.origin[2] + k_end * h
        action = LayerAction(z0_mm=float(z0), z1_mm=float(z1), reinforce_xy=reinforce, relax_xy=relax, mean_utilization=mean_u, p95_utilization=p95_u, n_voxels=n_vox, median_utilization=med_u, occupied_xy=col_occupied)
        plan.actions.append(action)
        if reinforce.any():
            plan.n_reinforced_layers += 1
        if relax.any():
            plan.n_relaxed_layers += 1
        k = k_end
    all_vals = util[occ]
    plan.global_mean_utilization = float(all_vals.mean()) if all_vals.size else 0.0
    return plan

def region_boundary_length_mm(reinforce_xy: np.ndarray, h: float) -> float:
    if not reinforce_xy.any():
        return 0.0
    padded = np.pad(reinforce_xy.astype(np.int8), 1)
    dx = np.abs(np.diff(padded, axis=1)).sum()
    dy = np.abs(np.diff(padded, axis=0)).sum()
    return float(dx + dy) * h

def plan_summary_table(plan: Plan, max_rows: int=12) -> str:
    lines = [f"{'z-range (mm)':>20} {'util mean':>10} {'util p95':>9} {'reinforce':>10} {'relax':>6}"]
    rows = plan.actions
    shown = rows if len(rows) <= max_rows else rows[:max_rows // 2] + [None] + rows[-(max_rows // 2):]
    for r in shown:
        if r is None:
            lines.append(f'  ... {len(rows) - max_rows} more layers ...')
            continue
        nr = int(r.reinforce_xy.sum())
        nl = int(r.relax_xy.sum())
        lines.append(f'{r.z0_mm:8.2f}-{r.z1_mm:7.2f} {r.mean_utilization:10.3f} {r.p95_utilization:9.3f} {nr:10d} {nl:6d}')
    return '\n'.join(lines)

# ======================================================================
# module: host_bridge
# ======================================================================
log = logging.getLogger('ecoslice.host')
SCALED_UNITS_PER_MM = 1000000.0
SCALE_GUESSES = (1000000.0, 1000.0, 1.0)
SOLID_ENUM_NAMES = ('stInternalSolid', 'stSolid', 'InternalSolid')
SPARSE_ENUM_NAMES = ('stInternal', 'Internal')
DOWNGRADABLE_ENUM_NAMES = ('stInternalSolid',)
SOLID_TYPE_NAMES = ('internal_solid', 'internalsolid', 'solid', 'stinternalsolid')
SPARSE_HINTS = ('internal', 'sparse', 'infill')

def _first_attr(obj, names, default=None):
    for n in names:
        v = getattr(obj, n, None)
        if v is not None:
            return v
    return default

def _call_or_attr(obj, name, default=None):
    try:
        v = getattr(obj, name)
    except AttributeError:
        return default
    if callable(v):
        try:
            return v()
        except Exception as exc:
            log.debug('calling %s() failed: %s', name, exc)
            return default
    return v

@dataclass
class HostCapabilities:
    mesh_source: str = 'none'
    surface_type_mode: str = 'unavailable'
    extra_perimeters_mode: str = 'unavailable'
    fill_surfaces_mode: str = 'unavailable'
    notes: list[str] = field(default_factory=list)

    def as_dict(self) -> dict:
        return {'mesh_source': self.mesh_source, 'surface_type_mode': self.surface_type_mode, 'extra_perimeters_mode': self.extra_perimeters_mode, 'fill_surfaces_mode': self.fill_surfaces_mode, 'notes': list(self.notes)}

def current_object(ctx):
    return getattr(ctx, 'object', None)

def iter_print_objects(ctx) -> list:
    obj = current_object(ctx)
    if obj is not None:
        return [obj]
    for attr in ('objects', 'print_objects', 'model_objects'):
        objs = _call_or_attr(ctx, attr)
        if objs:
            return list(objs)
    po = _call_or_attr(ctx, 'print') or _first_attr(ctx, ('print',))
    if po is not None:
        objs = _call_or_attr(po, 'objects')
        if objs:
            return list(objs)
    return []

def object_key(obj) -> str:
    oid = _call_or_attr(obj, 'id')
    if isinstance(oid, (int, str)):
        return f'obj{oid}'
    return f'obj@{id(obj):x}'

def _apply_affine(verts: np.ndarray, matrix) -> np.ndarray:
    if matrix is None:
        return verts
    m = np.asarray(matrix, dtype=np.float64)
    if m.shape != (4, 4):
        return verts
    return verts @ m[:3, :3].T + m[:3, 3]

def _mesh_arrays(mesh) -> tuple | None:
    verts = _call_or_attr(mesh, 'vertices')
    tris = _call_or_attr(mesh, 'triangles')
    if tris is None:
        tris = _call_or_attr(mesh, 'indices')
    if verts is None or tris is None:
        return None
    v = np.array(verts, dtype=np.float64, copy=True)
    t = np.array(tris, dtype=np.int64, copy=True)
    if v.ndim != 2 or v.shape[1] != 3 or t.ndim != 2 or (t.shape[1] != 3):
        return None
    return (v, t)

def get_mesh(print_object) -> tuple | None:
    """Mesh of a PrintObject in print coordinates (mm).

    OrcaSlicer hands out per-volume meshes in the volume's own local frame
    (PluginHostMesh.cpp), so volume->object (`ModelVolume.matrix()`) and
    object->print (`PrintObject.trafo()`) have to be applied before the geometry
    lines up with the sliced layers.
    """
    trafo = _call_or_attr(print_object, 'trafo')
    model_object = _call_or_attr(print_object, 'model_object')
    parts: list[tuple[np.ndarray, np.ndarray]] = []
    if model_object is not None:
        volumes = _call_or_attr(model_object, 'volumes') or []
        for vol in volumes:
            is_part = _call_or_attr(vol, 'is_model_part')
            if is_part is False:
                continue
            mesh = _call_or_attr(vol, 'mesh')
            arrays = _mesh_arrays(mesh) if mesh is not None else None
            if arrays is None:
                continue
            v, t = arrays
            parts.append((_apply_affine(v, _call_or_attr(vol, 'matrix')), t))
    if not parts:
        arrays = _mesh_arrays(print_object)
        if arrays is None:
            mesh = _first_attr(print_object, ('mesh', 'raw_mesh'))
            arrays = _mesh_arrays(mesh) if mesh is not None else None
        if arrays is None:
            return None
        parts.append(arrays)
    verts = []
    tris = []
    offset = 0
    for v, t in parts:
        verts.append(v)
        tris.append(t + offset)
        offset += v.shape[0]
    v_all = _apply_affine(np.vstack(verts), trafo)
    return (v_all.astype(np.float32), np.vstack(tris).astype(np.int32))

def object_footprint_mm(print_object) -> tuple | None:
    bb = _call_or_attr(print_object, 'bounding_box')
    if bb is None:
        return None
    try:
        values = [float(x) for x in bb]
    except TypeError:
        return None
    if len(values) != 4:
        return None
    min_x, min_y, max_x, max_y = values
    return (min_x / SCALED_UNITS_PER_MM, min_y / SCALED_UNITS_PER_MM, max_x / SCALED_UNITS_PER_MM, max_y / SCALED_UNITS_PER_MM)

def iter_layers(print_object) -> list:
    layers = _call_or_attr(print_object, 'layers')
    if layers:
        return list(layers)
    return []

def iter_regions(layer) -> list:
    regions = _call_or_attr(layer, 'regions')
    if regions:
        return list(regions)
    return []

def get_fill_surfaces(region) -> list:
    """Surfaces of a LayerRegion.

    `LayerRegion.fill_surfaces` is a `SurfaceCollection`, not a sequence: its
    `.surfaces` property is what yields live `Surface` references.
    """
    fs = getattr(region, 'fill_surfaces', None)
    if fs is None:
        return []
    surfaces = getattr(fs, 'surfaces', None)
    if surfaces is not None and (not callable(surfaces)):
        return list(surfaces)
    if isinstance(fs, (list, tuple)):
        return list(fs)
    try:
        return list(fs)
    except TypeError:
        log.debug('fill_surfaces of %r is neither a collection nor iterable', type(fs).__name__)
        return []

def get_layer_z(layer) -> tuple[float, float] | None:
    pz = _call_or_attr(layer, 'print_z')
    hh = _call_or_attr(layer, 'height')
    if pz is None:
        slice_z = _call_or_attr(layer, 'slice_z')
        if slice_z is None:
            return None
        z = float(slice_z)
        return (z - 0.1, z + 0.1)
    z = float(pz)
    h = float(hh) if hh else 0.2
    return (z - h, z)

def _contour_of(surface):
    expoly = _first_attr(surface, ('expolygon', 'expoly', 'poly'))
    if expoly is None:
        return None
    return _first_attr(expoly, ('contour', 'outer', 'polygon'))

def _contour_centroid_scaled(contour) -> tuple[float, float] | None:
    centroid = _call_or_attr(contour, 'centroid')
    if centroid is not None:
        x = getattr(centroid, 'x', None)
        y = getattr(centroid, 'y', None)
        if x is not None and y is not None:
            return (float(x), float(y))
    arr = _call_or_attr(contour, 'as_array')
    if arr is not None:
        a = np.asarray(arr, dtype=np.float64)
        if a.ndim == 2 and a.shape[1] == 2 and (a.shape[0] > 0):
            return (float(a[:, 0].mean()), float(a[:, 1].mean()))
    pts = _first_attr(contour, ('points', 'pts'))
    if pts is None:
        return None
    sx = sy = 0.0
    count = 0
    for p in pts:
        x = getattr(p, 'x', None)
        y = getattr(p, 'y', None)
        if x is None:
            try:
                x, y = (p[0], p[1])
            except Exception:
                continue
        sx += float(x)
        sy += float(y)
        count += 1
    if count == 0:
        return None
    return (sx / count, sy / count)

def _contour_points_scaled(contour) -> np.ndarray | None:
    arr = _call_or_attr(contour, 'as_array')
    if arr is not None:
        a = np.asarray(arr, dtype=np.float64)
        if a.ndim == 2 and a.shape[1] == 2 and (a.shape[0] > 0):
            return a
    pts = _first_attr(contour, ('points', 'pts'))
    if pts is None:
        return None
    rows = []
    for p in pts:
        x = getattr(p, 'x', None)
        y = getattr(p, 'y', None)
        if x is None:
            try:
                x, y = (p[0], p[1])
            except Exception:
                continue
        rows.append((float(x), float(y)))
    if not rows:
        return None
    return np.asarray(rows, dtype=np.float64)

def slice_bbox_mm(print_object, max_layers: int=16) -> tuple | None:
    """Bounding box of the sliced fill polygons, in mm, in the frame the host
    keeps layer geometry in.

    OrcaSlicer keeps fill_surfaces in the object-local frame while the mesh
    (after `trafo()`) sits in the plate frame; this bbox is the ground truth
    for anchoring the analysis grid onto the slices regardless of either
    frame's origin.
    """
    min_pt = None
    max_pt = None
    layers_with_points = 0
    for layer in iter_layers(print_object):
        if layers_with_points >= max_layers:
            break
        lo = hi = None
        for region in iter_regions(layer):
            for surface in get_fill_surfaces(region):
                contour = _contour_of(surface)
                if contour is None:
                    continue
                a = _contour_points_scaled(contour)
                if a is None:
                    continue
                lo = a.min(axis=0) if lo is None else np.minimum(lo, a.min(axis=0))
                hi = a.max(axis=0) if hi is None else np.maximum(hi, a.max(axis=0))
        if lo is None or hi is None:
            continue
        layers_with_points += 1
        min_pt = lo if min_pt is None else np.minimum(min_pt, lo)
        max_pt = hi if max_pt is None else np.maximum(max_pt, hi)
    if min_pt is None or max_pt is None:
        return None
    extent = float(((max_pt - min_pt) ** 2).sum() ** 0.5)
    scale = SCALED_UNITS_PER_MM
    for s in SCALE_GUESSES:
        if 0.01 < extent / s < 100000.0:
            scale = s
            break
    return (float(min_pt[0]) / scale, float(min_pt[1]) / scale, float(max_pt[0]) / scale, float(max_pt[1]) / scale)

def surface_outline_mm(surface, scale: float | None=None) -> np.ndarray | None:
    """Contour points of a fill surface as (N,2) mm coordinates."""
    contour = _contour_of(surface)
    if contour is None:
        return None
    a = _contour_points_scaled(contour)
    if a is None:
        return None
    if scale is None:
        scale = guess_scale(surface)
    return a / scale

def surface_centroid_xy_mm(surface, scale: float | None=None) -> tuple[float, float] | None:
    contour = _contour_of(surface)
    if contour is None:
        return None
    c = _contour_centroid_scaled(contour)
    if c is None:
        return None
    mx, my = c
    if scale is not None:
        return (mx / scale, my / scale)
    for s in SCALE_GUESSES:
        if 0.001 < abs(mx) / s < 100000.0:
            return (mx / s, my / s)
    return (mx, my)

def guess_scale(surface) -> float:
    area = _call_or_attr(surface, 'area')
    if area and abs(area) > 0:
        for s in SCALE_GUESSES:
            side = (abs(area) / (s * s)) ** 0.5
            if 0.001 < side < 10000.0:
                return s
    return SCALED_UNITS_PER_MM

def get_surface_type(surface):
    return _first_attr(surface, ('surface_type', 'type_'), None)

def solid_surface_type(surface, fallback: str='internal_solid'):
    """The value to assign to `Surface.surface_type` for solid infill.

    Inside OrcaSlicer the field is a `SurfaceType` pybind enum, so the enum
    member is resolved from the live value's own type; string mode is only for
    hosts (and tests) that model the field as text.
    """
    current = get_surface_type(surface)
    if current is None or isinstance(current, str):
        return fallback
    cls = type(current)
    for name in SOLID_ENUM_NAMES:
        member = getattr(cls, name, None)
        if member is not None:
            return member
    return fallback

def sparse_surface_type(surface, fallback: str='internal'):
    """The value meaning ordinary sparse internal infill, resolved like `solid_surface_type`."""
    current = get_surface_type(surface)
    if current is None or isinstance(current, str):
        return fallback
    cls = type(current)
    for name in SPARSE_ENUM_NAMES:
        member = getattr(cls, name, None)
        if member is not None:
            return member
    return fallback

def is_downgradable_solid(surface) -> bool:
    """True only for density-driven internal solid infill (`stInternalSolid`).

    Top, bottom and every bridge variant are load-bearing or visible shells that
    the slicer created for a reason, so they are never candidates for being
    thinned back out to sparse — only the internal solid the shell-thickness
    logic added is.
    """
    st = get_surface_type(surface)
    if st is None:
        return False
    if isinstance(st, str):
        return st.strip().lower().replace('_', '') in ('internalsolid', 'stinternalsolid')
    name = getattr(st, 'name', None) or str(st).rsplit('.', 1)[-1]
    return name in DOWNGRADABLE_ENUM_NAMES

def set_surface_sparse(surface) -> bool:
    """Reclassify a solid internal surface back to sparse infill."""
    if not is_downgradable_solid(surface):
        return False
    value = sparse_surface_type(surface)
    for attr in ('surface_type', 'type_'):
        if hasattr(surface, attr):
            try:
                setattr(surface, attr, value)
                return True
            except Exception as exc:
                log.debug('set_surface_sparse failed on %r: %s', attr, exc)
    return False

def set_surface_type(surface, solid_type=None) -> bool:
    value = solid_type
    if value is None or isinstance(value, str):
        resolved = solid_surface_type(surface, fallback=value or 'internal_solid')
        value = resolved
    for attr in ('surface_type', 'type_'):
        if hasattr(surface, attr):
            try:
                setattr(surface, attr, value)
                return True
            except Exception as exc:
                log.debug('set_surface_type failed on %r: %s', attr, exc)
    return False

def is_sparse_like(surface) -> bool:
    is_solid = _call_or_attr(surface, 'is_solid')
    is_internal = _call_or_attr(surface, 'is_internal')
    if isinstance(is_solid, bool) and isinstance(is_internal, bool):
        return is_internal and (not is_solid)
    if isinstance(is_solid, bool):
        return not is_solid
    st = get_surface_type(surface)
    if st is None:
        return True
    name = str(st).lower()
    return any((h in name for h in SPARSE_HINTS)) and (not any((s in name for s in SOLID_TYPE_NAMES)))

def get_extra_perimeters(surface) -> int:
    ep = _first_attr(surface, ('extra_perimeters',), None)
    try:
        return int(ep) if ep is not None else 0
    except (TypeError, ValueError):
        return 0

def set_extra_perimeters(surface, value: int) -> bool:
    if hasattr(surface, 'extra_perimeters'):
        try:
            setattr(surface, 'extra_perimeters', int(value))
            return True
        except Exception as exc:
            log.debug('set_extra_perimeters failed: %s', exc)
    return False

def probe(ctx) -> HostCapabilities:
    cap = HostCapabilities()
    objs = iter_print_objects(ctx)
    if not objs:
        cap.notes.append('no print objects found via known ctx paths')
        return cap
    mesh = get_mesh(objs[0])
    cap.mesh_source = type(objs[0]).__name__ + ('+mesh' if mesh else '-no-mesh')
    layers = iter_layers(objs[0])
    for layer in layers[:5]:
        for region in iter_regions(layer):
            surfaces = get_fill_surfaces(region)
            if surfaces:
                s = surfaces[0]
                st = get_surface_type(s)
                cap.surface_type_mode = 'unavailable' if st is None else 'string' if isinstance(st, str) else type(st).__name__
                cap.extra_perimeters_mode = 'writable' if hasattr(s, 'extra_perimeters') else 'missing'
                cap.fill_surfaces_mode = f'n={len(surfaces)}'
                return cap
    cap.notes.append('no fill_surfaces found in first layers')
    return cap

# ======================================================================
# module: mutate
# ======================================================================
@dataclass
class MutationConfig:
    add_perimeters: int = 2
    max_extra_perimeters: int = 4
    enable_solid_infill: bool = True
    enable_relax: bool = True
    solid_type: str = 'internal_solid'
    enable_solid_downgrade: bool = False

@dataclass
class MutationStats:
    surfaces_reinforced: int = 0
    surfaces_solidified: int = 0
    surfaces_relaxed: int = 0
    surfaces_desolidified: int = 0
    surfaces_skipped_no_xy: int = 0
    perimeters_added: int = 0
    perimeters_removed: int = 0

    def merge(self, other: 'MutationStats') -> None:
        self.surfaces_reinforced += other.surfaces_reinforced
        self.surfaces_solidified += other.surfaces_solidified
        self.surfaces_relaxed += other.surfaces_relaxed
        self.surfaces_desolidified += other.surfaces_desolidified
        self.surfaces_skipped_no_xy += other.surfaces_skipped_no_xy
        self.perimeters_added += other.perimeters_added
        self.perimeters_removed += other.perimeters_removed

@dataclass(frozen=True)
class FrameAlignment:
    """Translation from slicer coordinates into the analysis grid's frame.

    The analysed mesh and the sliced polygons need not share an origin (the
    object is placed on the bed, and libslic3r keeps slices in the print
    object's own frame), so the plan is anchored by matching bounding boxes
    rather than by trusting either origin.
    """
    dx: float = 0.0
    dy: float = 0.0
    dz: float = 0.0

    def to_grid_xy(self, x_mm: float, y_mm: float) -> tuple[float, float]:
        return (x_mm - self.dx, y_mm - self.dy)

    def to_grid_z(self, z_mm: float) -> float:
        return z_mm - self.dz

def compute_alignment(print_object, grid, layers=None) -> FrameAlignment:
    dx = dy = dz = 0.0
    bbox = slice_bbox_mm(print_object)
    if bbox is not None and bbox[2] > bbox[0] and (bbox[3] > bbox[1]):
        dx = bbox[0] - float(grid.origin[0])
        dy = bbox[1] - float(grid.origin[1])
    else:
        footprint = object_footprint_mm(print_object)
        if footprint is not None:
            min_x, min_y, max_x, max_y = footprint
            if max_x > min_x and max_y > min_y:
                dx = min_x - float(grid.origin[0])
                dy = min_y - float(grid.origin[1])
    layers = iter_layers(print_object) if layers is None else layers
    for layer in layers:
        zr = get_layer_z(layer)
        if zr is not None:
            dz = zr[0] - float(grid.origin[2])
            break
    return FrameAlignment(dx=dx, dy=dy, dz=dz)

def _classify_xy(x_mm: float, y_mm: float, action: LayerAction, grid) -> str:
    x0, y0 = (float(grid.origin[0]), float(grid.origin[1]))
    h = grid.h
    i = int((x_mm - x0) / h)
    j = int((y_mm - y0) / h)
    nx, ny = action.reinforce_xy.shape
    if not (0 <= i < nx and 0 <= j < ny):
        return 'outside'
    if action.reinforce_xy[i, j]:
        return 'reinforce'
    if action.relax_xy[i, j]:
        return 'relax'
    return 'neutral'

def _classify_outline(outline_xy, action: LayerAction, grid) -> str:
    """Classify a surface by the mask cells its outline touches.

    Real parts slice into few large surfaces (a whole layer can be ONE
    rectangle spanning the hot and cold zones), so classifying by centroid
    alone reads 'neutral' and skips them. Any outline point inside a
    reinforce column wins; relax only when no hot overlap exists.
    """
    x0, y0 = (float(grid.origin[0]), float(grid.origin[1]))
    h = grid.h
    nx, ny = action.reinforce_xy.shape
    i = np.floor((outline_xy[:, 0] - x0) / h).astype(int)
    j = np.floor((outline_xy[:, 1] - y0) / h).astype(int)
    i = np.clip(i, 0, nx - 1)
    j = np.clip(j, 0, ny - 1)
    inside = (outline_xy[:, 0] >= x0) & (outline_xy[:, 0] < x0 + nx * h) & (outline_xy[:, 1] >= y0) & (outline_xy[:, 1] < y0 + ny * h)
    if not inside.any():
        return 'outside'
    if action.reinforce_xy[i[inside], j[inside]].any():
        return 'reinforce'
    if action.relax_xy[i[inside], j[inside]].any():
        return 'relax'
    return 'neutral'

def _classify_surface(surface, action: LayerAction, grid, scale, alignment: FrameAlignment) -> str:
    outline = surface_outline_mm(surface, scale=scale)
    if outline is not None and outline.shape[0] > 0:
        grid_xy = np.column_stack((outline[:, 0] - alignment.dx, outline[:, 1] - alignment.dy))
        cls = _classify_outline(grid_xy, action, grid)
        if cls != 'neutral':
            return cls
    xy = surface_centroid_xy_mm(surface, scale=scale)
    if xy is None:
        return 'no_xy'
    return _classify_xy(*alignment.to_grid_xy(xy[0], xy[1]), action, grid)

def apply_to_region(region, action: LayerAction, grid, cfg: MutationConfig, alignment: FrameAlignment | None=None) -> MutationStats:
    stats = MutationStats()
    align = alignment or FrameAlignment()
    scale = None
    for surface in get_fill_surfaces(region):
        if scale is None:
            scale = guess_scale(surface)
        cls = _classify_surface(surface, action, grid, scale, align)
        if cls == 'no_xy':
            stats.surfaces_skipped_no_xy += 1
            continue
        if cls == 'reinforce':
            cur = get_extra_perimeters(surface)
            target = min(cur + cfg.add_perimeters, cfg.max_extra_perimeters)
            if target != cur and set_extra_perimeters(surface, target):
                stats.surfaces_reinforced += 1
                stats.perimeters_added += target - cur
            if cfg.enable_solid_infill and is_sparse_like(surface):
                if set_surface_type(surface, cfg.solid_type):
                    stats.surfaces_solidified += 1
        elif cls == 'relax' and cfg.enable_relax:
            cur = get_extra_perimeters(surface)
            if cur > 0 and set_extra_perimeters(surface, 0):
                stats.surfaces_relaxed += 1
                stats.perimeters_removed += cur
            if cfg.enable_solid_downgrade and is_downgradable_solid(surface):
                if set_surface_sparse(surface):
                    stats.surfaces_desolidified += 1
    return stats

def apply_plan_to_object(print_object, plan, grid, cfg: MutationConfig, alignment: FrameAlignment | None=None) -> MutationStats:
    total = MutationStats()
    layers = iter_layers(print_object)
    align = alignment if alignment is not None else compute_alignment(print_object, grid, layers)
    for layer in layers:
        zr = get_layer_z(layer)
        if zr is None:
            continue
        z_mid = align.to_grid_z((zr[0] + zr[1]) * 0.5)
        for action in plan.actions:
            if action.z0_mm <= z_mid < action.z1_mm or (action is plan.actions[-1] and z_mid == action.z1_mm):
                for region in iter_regions(layer):
                    total.merge(apply_to_region(region, action, grid, cfg, align))
                break
    return total

# ======================================================================
# module: receipt
# ======================================================================
PLA_DENSITY_G_CM3 = 1.24
PLA_VIRGIN_KG_CO2E_PER_KG = 5.76
PLA_RECYCLED_KG_CO2E_PER_KG = 2.47
PRINTER_WATTS_DEFAULT = 100.0
PRINTER_WATTS_RANGE = (80.0, 125.0)
KWH_PER_HOUR_AT_DEFAULT_W = PRINTER_WATTS_DEFAULT / 1000.0
CITATIONS = ('FDM power draw 80-125W on PLA (measured desktop FDM range)', 'Prusa Material LCA: virgin PLA 5.76 kgCO2e/kg; recycled PLA 2.47 kgCO2e/kg')

def grams_from_volume_mm3(volume_mm3: float, density_g_cm3: float=PLA_DENSITY_G_CM3) -> float:
    return volume_mm3 * 0.001 * density_g_cm3

def co2e_g(grams_filament: float, recycled: bool=False) -> float:
    factor = PLA_RECYCLED_KG_CO2E_PER_KG if recycled else PLA_VIRGIN_KG_CO2E_PER_KG
    return grams_filament / 1000.0 * factor * 1000.0

def energy_kwh(print_hours: float, watts: float=PRINTER_WATTS_DEFAULT) -> float:
    return print_hours * watts / 1000.0
FILAMENT_G_RE = re.compile(';\\s*filament used \\[g\\]\\s*[:=]?\\s*([\\d.,]+)', re.IGNORECASE)
FILAMENT_CM3_RE = re.compile(';\\s*filament used \\[cm3\\]\\s*[:=]?\\s*([\\d.,]+)', re.IGNORECASE)
PRINT_TIME_RE = re.compile(';\\s*estimated printing time \\(normal mode\\)\\s*[:=]?\\s*(.+)', re.IGNORECASE)
_TIME_UNITS_RE = re.compile('(?:(\\d+)\\s*d)?\\s*(?:(\\d+)\\s*h)?\\s*(?:(\\d+)\\s*m)?\\s*(?:(\\d+(?:\\.\\d+)?)\\s*s)?', re.IGNORECASE)

def parse_duration_seconds(text: str) -> float | None:
    """Seconds from an OrcaSlicer/PrusaSlicer duration footer ("1h 54m 12s")."""
    m = _TIME_UNITS_RE.match(text.strip())
    if not m or not any(m.groups()):
        return None
    d, h, mi, sec = (float(x) if x else 0.0 for x in m.groups())
    return d * 86400.0 + h * 3600.0 + mi * 60.0 + sec

def parse_gcode_footer(gcode_text: str) -> dict:
    """Authoritative filament/time numbers straight out of the exported G-code.

    These are the slicer's own totals for the print EcoSlice just shaped, so the
    receipt can quote measured mass, time and energy instead of only a model.
    Our own ``;ECOSLICE`` lines are skipped so a re-run never reads its own output.
    """
    out: dict = {'filament_g': None, 'filament_cm3': None, 'print_time_s': None}
    for line in gcode_text.splitlines():
        line = line.strip()
        if not line.startswith(';') or line.startswith(';ECOSLICE'):
            continue
        if out['filament_g'] is None:
            m = FILAMENT_G_RE.match(line)
            if m:
                out['filament_g'] = float(m.group(1).replace(',', '.'))
                continue
        if out['filament_cm3'] is None:
            m = FILAMENT_CM3_RE.match(line)
            if m:
                out['filament_cm3'] = float(m.group(1).replace(',', '.'))
                continue
        if out['print_time_s'] is None:
            m = PRINT_TIME_RE.match(line)
            if m:
                out['print_time_s'] = parse_duration_seconds(m.group(1))
    return out

def format_duration(seconds: float) -> str:
    seconds = max(0.0, float(seconds))
    h, rem = divmod(int(round(seconds)), 3600)
    m, s = divmod(rem, 60)
    if h:
        return f'{h}h{m:02d}m'
    if m:
        return f'{m}m{s:02d}s'
    return f'{s}s'

@dataclass
class SavingsEstimate:
    added_grams: float
    uniform_baseline_grams: float
    saved_vs_uniform_grams: float
    co2e_saved_vs_uniform_g: float

    def as_dict(self) -> dict:
        return {'added_grams': round(self.added_grams, 3), 'uniform_baseline_grams': round(self.uniform_baseline_grams, 3), 'saved_vs_uniform_grams': round(self.saved_vs_uniform_grams, 3), 'co2e_saved_vs_uniform_g': round(self.co2e_saved_vs_uniform_g, 3)}

def _num(value, spec='{:.2f}') -> str:
    try:
        return spec.format(float(value))
    except (TypeError, ValueError):
        return str(value)

def _mutation_line(stats: dict, label: str, layers_key: str, count_key: str, noun: str) -> str:
    """Distinguish "no mutations ran" (analysis only) from "ran and changed nothing"."""
    layers = stats.get(layers_key, 0)
    if count_key not in stats:
        return f';ECOSLICE {label}: {layers} layers planned (applied during slicing)'
    return f';ECOSLICE {label}: {layers} layers, {stats[count_key]} {noun}'
RECEIPT_BEGIN = ';ECOSLICE BEGIN ----------------------------------------------------------'
RECEIPT_END = ';ECOSLICE END ------------------------------------------------------------'

def _measured_lines(stats: dict) -> list[str]:
    """Lines quoting the slicer's own export footer, when the receipt has it.

    Everything above these lines is EcoSlice's model of the print; these are what
    the print actually costs, so they are labelled measured and kept separate.
    """
    lines: list[str] = []
    grams = stats.get('measured_filament_g')
    seconds = stats.get('measured_print_time_s')
    if grams is None and seconds is None:
        return lines
    if grams is not None:
        lines.append(f";ECOSLICE measured mass   : {_num(grams)} g ({_num(co2e_g(grams), '{:.1f}')} gCO2e virgin PLA)")
    if seconds is not None:
        kwh = energy_kwh(seconds / 3600.0)
        lines.append(f';ECOSLICE measured time   : {format_duration(seconds)} = {kwh:.3f} kWh at {PRINTER_WATTS_DEFAULT:.0f} W')
    return lines

def format_receipt(stats: dict) -> list[str]:
    lines = [RECEIPT_BEGIN, f";ECOSLICE mode            : {stats.get('mode', 'n/a')}", f";ECOSLICE load case       : {stats.get('load_case', 'n/a')}", f";ECOSLICE safety factor   : {_num(stats.get('safety_factor'))}", f";ECOSLICE allowable stress: {_num(stats.get('allowable_mpa'), '{:.1f}')} MPa (yield/sf)", f";ECOSLICE max von Mises   : {_num(stats.get('max_vm_mpa'), '{:.1f}')} MPa", f";ECOSLICE solver          : {stats.get('solver', 'n/a')} | voxels {stats.get('voxels', 'n/a')}"]
    if 'confidence' in stats:
        lines.append(f";ECOSLICE confidence      : {_num(stats.get('confidence'))} ({stats.get('confidence_label', 'n/a')}) - heuristic, not a certification")
        if stats.get('confidence_reasons'):
            lines.append(f";ECOSLICE confidence why  : {stats['confidence_reasons']}")
    lines += [_mutation_line(stats, 'reinforced      ', 'reinforced_layers', 'perimeters_added', 'extra perimeter-lines added'), _mutation_line(stats, 'relaxed         ', 'relaxed_layers', 'perimeters_removed', 'perimeter-lines removed'), f";ECOSLICE reinforcement   : +{_num(stats.get('added_grams'))} g localized (walls +{_num(stats.get('added_wall_grams'))} g, solid infill +{_num(stats.get('added_infill_grams'))} g)", f";ECOSLICE vs blanket-strengthened baseline: -{_num(stats.get('saved_vs_uniform_grams'))} g (-{_num(stats.get('co2e_saved_vs_uniform_g'), '{:.1f}')} gCO2e virgin PLA)"]
    lines += _measured_lines(stats)
    lines += [';ECOSLICE sources: ' + ' | '.join(CITATIONS), ";ECOSLICE model-vs-measured: the +g / -g lines above are EcoSlice's model; 'measured' lines are the slicer's own export footer", RECEIPT_END]
    return lines

def receipt_block(stats: dict) -> str:
    return '\n'.join(format_receipt(stats)) + '\n'

# ======================================================================
# module: options
# ======================================================================
DEFAULT_LINE_WIDTH_MM = 0.42
DEFAULT_SPARSE_INFILL_DENSITY = 0.15
NOMINAL_FLOW_MM3_S = 8.0
CONFIDENCE_LABELS = ((0.75, 'high'), (0.5, 'moderate'), (0.0, 'low'))
OVER_ALLOWABLE_SCORE_CAP = 0.6

@dataclass
class Confidence:
    """Heuristic trust score for a plan — explicitly not an engineering certification."""
    score: float
    label: str
    reasons: list[str] = field(default_factory=list)

    def as_dict(self) -> dict:
        return {'confidence': round(self.score, 2), 'confidence_label': self.label, 'confidence_reasons': '; '.join(self.reasons)}

def _label_for(score: float) -> str:
    for threshold, label in CONFIDENCE_LABELS:
        if score >= threshold:
            return label
    return 'low'

def strength_confidence(plan: Plan, grid, von_mises: np.ndarray, at_risk_frac: float=1.0) -> Confidence:
    """Blend stress margin, hotspot coverage and mesh adequacy into one 0-1 score.

    Three things can make a plan untrustworthy and each is scored separately so
    the receipt can say *which* one is weak: the part may be over its allowable
    stress however it is reinforced, the reinforcement may miss hotspots, or the
    voxel grid may be too coarse through the thin direction to resolve bending
    at all.

    Coverage is measured against voxels *at or over* the allowable stress, not
    against the planner's lower reinforce threshold: a part comfortably inside
    its margin has nothing at risk, and must not be marked down for the planner
    correctly deciding it needs no extra material.
    """
    reasons: list[str] = []
    allowable = plan.allowable_mpa or 1e-09
    util_max = float(plan.max_vm_mpa) / allowable
    over_allowable = util_max > 1.0
    if util_max <= 0.8:
        margin = 1.0
        reasons.append(f'peak stress {util_max:.2f}x allowable - inside margin')
    elif util_max <= 1.0:
        margin = float(1.0 - 0.4 * (util_max - 0.8) / 0.2)
        reasons.append(f'peak stress {util_max:.2f}x allowable - close to the limit')
    elif util_max >= 2.0:
        margin = 0.0
        reasons.append(f'peak stress {util_max:.2f}x allowable - part is under-sized, not a wall problem')
    else:
        margin = float(0.6 * (2.0 - util_max))
        reasons.append(f'peak stress {util_max:.2f}x allowable - OVER the allowable, reinforcement alone will not fix this')
    hot_total = 0
    hot_covered = 0
    h = grid.h
    origin_z = float(grid.origin[2])
    util = np.zeros_like(von_mises)
    occ = grid.mask & (von_mises > 0)
    util[occ] = von_mises[occ] / allowable
    for action in plan.actions:
        k0 = int(round((action.z0_mm - origin_z) / h))
        k1 = int(round((action.z1_mm - origin_z) / h))
        band = util[:, :, k0:k1]
        if band.size == 0:
            continue
        hot = band >= at_risk_frac
        n_hot = int(hot.sum())
        if n_hot == 0:
            continue
        hot_total += n_hot
        hot_covered += int((hot & action.reinforce_xy[:, :, None]).sum())
    if hot_total == 0:
        coverage = 1.0
        reasons.append('no voxel reaches the allowable stress - nothing at risk')
    else:
        coverage = hot_covered / hot_total
        reasons.append(f'{coverage * 100:.0f}% of at-risk voxels sit under reinforced columns')
    cells_across = int(min(grid.shape))
    if cells_across >= 8:
        mesh = 1.0
    elif cells_across >= 4:
        mesh = 0.5 + 0.5 * (cells_across - 4) / 4.0
    else:
        mesh = 0.25
        reasons.append(f'only {cells_across} cells across the thinnest axis - bending is under-resolved')
    if cells_across >= 8:
        reasons.append(f'{cells_across} cells across the thinnest axis')
    elif cells_across >= 4:
        reasons.append(f'{cells_across} cells across the thinnest axis - coarse for bending')
    score = 0.45 * margin + 0.35 * coverage + 0.2 * mesh
    if over_allowable:
        score = min(score, OVER_ALLOWABLE_SCORE_CAP)
    score = float(min(max(score, 0.0), 1.0))
    return Confidence(score=score, label=_label_for(score), reasons=reasons)

def estimate_material(plan: Plan, grid, *, add_perimeters: int, layer_height_mm: float, enable_solid_infill: bool=True, infill_density: float=DEFAULT_SPARSE_INFILL_DENSITY, line_width_mm: float=DEFAULT_LINE_WIDTH_MM) -> dict:
    """Material a plan adds, split into wall lines and solid-infill fill-in.

    Both levers are counted: extra perimeters trace the *boundary* of each
    reinforced region, while reclassifying sparse infill to solid fills its
    *area* from the profile's sparse density up to 100%. The solid term is
    usually the larger of the two, which is why it cannot be left out.

    The "uniform" figure is the same treatment applied to the whole occupied
    footprint of every band — the blanket-strengthening baseline the savings
    claim is measured against.
    """
    lh = layer_height_mm if layer_height_mm and layer_height_mm > 0 else 0.2
    h = grid.h
    fill_fraction = max(0.0, 1.0 - float(infill_density)) if enable_solid_infill else 0.0
    wall_vol = uniform_wall_vol = 0.0
    infill_vol = uniform_infill_vol = 0.0
    cell_area = h * h
    for a in plan.actions:
        n_print_layers = max(1, int(round((a.z1_mm - a.z0_mm) / lh)))
        occupied = a.occupied_xy if a.occupied_xy is not None else np.ones_like(a.reinforce_xy)
        hot_len = region_boundary_length_mm(a.reinforce_xy, h)
        all_len = region_boundary_length_mm(occupied, h)
        wall_vol += hot_len * add_perimeters * line_width_mm * lh * n_print_layers
        uniform_wall_vol += all_len * add_perimeters * line_width_mm * lh * n_print_layers
        hot_area = float(a.reinforce_xy.sum()) * cell_area
        all_area = float(occupied.sum()) * cell_area
        infill_vol += hot_area * fill_fraction * lh * n_print_layers
        uniform_infill_vol += all_area * fill_fraction * lh * n_print_layers
    added_wall_g = grams_from_volume_mm3(wall_vol)
    added_infill_g = grams_from_volume_mm3(infill_vol)
    added_g = added_wall_g + added_infill_g
    uniform_g = grams_from_volume_mm3(uniform_wall_vol + uniform_infill_vol)
    saved = max(uniform_g - added_g, 0.0)
    added_volume = wall_vol + infill_vol
    added_time_s = added_volume / NOMINAL_FLOW_MM3_S if NOMINAL_FLOW_MM3_S > 0 else 0.0
    return {'added_wall_grams': round(added_wall_g, 3), 'added_infill_grams': round(added_infill_g, 3), 'added_grams': round(added_g, 3), 'uniform_baseline_grams': round(uniform_g, 3), 'saved_vs_uniform_grams': round(saved, 3), 'co2e_saved_vs_uniform_g': round(co2e_g(saved), 2), 'added_co2e_g': round(co2e_g(added_g), 2), 'added_print_time_s': round(added_time_s, 1), 'added_energy_kwh': round(energy_kwh(added_time_s / 3600.0), 4)}

@dataclass(frozen=True)
class OptionPreset:
    """One of the three transparent choices offered for a part."""
    key: str
    name: str
    blurb: str
    add_perimeters: int
    max_extra_perimeters: int
    enable_solid_infill: bool
    enable_relax: bool
    reinforce_frac: float
    relax_frac: float
PRESETS: tuple[OptionPreset, ...] = (OptionPreset(key='eco', name='Eco', blurb='reinforce only true hotspots, relax aggressively elsewhere', add_perimeters=1, max_extra_perimeters=2, enable_solid_infill=False, enable_relax=True, reinforce_frac=0.8, relax_frac=0.35), OptionPreset(key='balanced', name='Balanced', blurb='walls and solid infill where stress demands, relax cold bands', add_perimeters=2, max_extra_perimeters=4, enable_solid_infill=True, enable_relax=True, reinforce_frac=0.6, relax_frac=0.2), OptionPreset(key='max_strength', name='Maximum Strength', blurb='widen the reinforced zone, no relaxation anywhere', add_perimeters=3, max_extra_perimeters=6, enable_solid_infill=True, enable_relax=False, reinforce_frac=0.4, relax_frac=0.0))
PRESETS_BY_KEY = {p.key: p for p in PRESETS}

@dataclass
class OptionReport:
    preset: OptionPreset
    plan: Plan
    confidence: Confidence
    material: dict

    def as_dict(self) -> dict:
        d = {'key': self.preset.key, 'name': self.preset.name, 'blurb': self.preset.blurb, 'reinforced_layers': self.plan.n_reinforced_layers, 'relaxed_layers': self.plan.n_relaxed_layers}
        d.update(self.material)
        d.update(self.confidence.as_dict())
        return d

def build_options(grid, von_mises: np.ndarray, *, yield_mpa: float, safety_factor: float, layer_height_mm: float | None=None, infill_density: float=DEFAULT_SPARSE_INFILL_DENSITY, presets: tuple[OptionPreset, ...]=PRESETS) -> list[OptionReport]:
    """Eco / Balanced / Maximum Strength from a single FEM solve.

    Only the plan thresholds and mutation strength change between options, so the
    stress field is solved once and re-thresholded — three options cost three
    cheap passes over the von Mises field, not three solves.
    """
    reports: list[OptionReport] = []
    for preset in presets:
        plan = plan_from_stress(grid, von_mises, yield_mpa=yield_mpa, safety_factor=safety_factor, layer_height_mm=layer_height_mm, reinforce_frac=preset.reinforce_frac, relax_frac=preset.relax_frac)
        material = estimate_material(plan, grid, add_perimeters=preset.add_perimeters, layer_height_mm=layer_height_mm or 0.2, enable_solid_infill=preset.enable_solid_infill, infill_density=infill_density)
        confidence = strength_confidence(plan, grid, von_mises)
        reports.append(OptionReport(preset=preset, plan=plan, confidence=confidence, material=material))
    return reports

def options_table(reports: list[OptionReport]) -> str:
    header = f"{'option':<18} {'+g':>7} {'wall':>7} {'infill':>7} {'-g vs blanket':>14} {'+time':>8} {'+kWh':>7} {'conf':>6}"
    lines = [header, '-' * len(header)]
    for r in reports:
        m = r.material
        lines.append(f"{r.preset.name:<18} {m['added_grams']:>7.2f} {m['added_wall_grams']:>7.2f} {m['added_infill_grams']:>7.2f} {m['saved_vs_uniform_grams']:>14.2f} {m['added_print_time_s'] / 60.0:>7.1f}m {m['added_energy_kwh']:>7.4f} {r.confidence.score:>5.2f} {r.confidence.label}")
    return '\n'.join(lines)

# ======================================================================
# module: pipeline
# ======================================================================
log = logging.getLogger('ecoslice')
DEFAULT_RESOLUTION = 32
MAX_ELEMENTS = 150000

@dataclass
class Analysis:
    object_key: str
    load_case: LoadCase
    grid: object
    fem: object
    plan: Plan
    wall_seconds: float
    savings: dict = field(default_factory=dict)
    notes: list[str] = field(default_factory=list)
    confidence: Confidence | None = None
    options: list[OptionReport] = field(default_factory=list)

    def stats(self, cfg: MutationConfig, mutation: MutationStats | None=None) -> dict:
        d = {'mode': 'load-aware walls & infill', 'load_case': self.load_case.description[:60] or '(unnamed)', 'load_case_source': self.load_case.source, 'safety_factor': self.load_case.safety_factor, 'allowable_mpa': self.plan.allowable_mpa, 'max_vm_mpa': self.plan.max_vm_mpa, 'solver': f'{self.fem.solver} @ {self.fem.n_dof} dof', 'voxels': f'{self.grid.shape[0]}x{self.grid.shape[1]}x{self.grid.shape[2]}', 'reinforced_layers': self.plan.n_reinforced_layers, 'relaxed_layers': self.plan.n_relaxed_layers, 'analysis_seconds': round(self.wall_seconds, 2)}
        if self.confidence is not None:
            d.update(self.confidence.as_dict())
        if self.notes:
            d['notes'] = '; '.join(self.notes)
        if mutation is not None:
            d['perimeters_added'] = mutation.perimeters_added
            d['perimeters_removed'] = mutation.perimeters_removed
            d['surfaces_solidified'] = mutation.surfaces_solidified
            d['surfaces_desolidified'] = mutation.surfaces_desolidified
        d.update(self.savings)
        return d

class EcoSlicePipeline:

    def __init__(self, cfg: MutationConfig | None=None, description: str | None=None, load_case: LoadCase | None=None, resolution: int=DEFAULT_RESOLUTION, layer_height_mm: float | None=None, infill_density: float=DEFAULT_SPARSE_INFILL_DENSITY):
        self.cfg = cfg or MutationConfig()
        self.description = description or ''
        self._explicit_load_case = load_case
        self.resolution = resolution
        self.layer_height_mm = layer_height_mm
        self.infill_density = infill_density
        self.analyses: dict[str, Analysis] = {}
        self.capabilities: HostCapabilities | None = None
        self._last_mutation: MutationStats | None = None

    def load_case_for(self, description: str) -> LoadCase:
        if self._explicit_load_case is not None:
            return self._explicit_load_case
        return extract_load_case(description)

    def _voxelize_within_budget(self, vertices, triangles, notes: list[str]):
        resolution = self.resolution
        previous = None
        while True:
            grid = voxelize(vertices, triangles, resolution=resolution)
            elements = int(grid.mask.sum())
            if elements == 0:
                raise ValueError('voxelization produced no solid cells — is the mesh closed?')
            if elements <= MAX_ELEMENTS or resolution <= 12 or elements == previous:
                return grid
            previous = elements
            resolution = max(12, int(resolution * (MAX_ELEMENTS / elements) ** (1 / 3)))
            notes.append(f'resolution reduced to {resolution} to stay under {MAX_ELEMENTS} elements')

    def _solver_faces(self, lc: LoadCase, notes: list[str]) -> tuple[list[str], str, np.ndarray]:
        constraint_faces = [c.face for c in lc.constraints]
        constrained = {canonical_face(f) for f in constraint_faces}
        total_force = np.zeros(3)
        primary = lc.forces[0]
        for f in lc.forces:
            total_force += np.asarray(f.normalized()) * f.magnitude_n
            if f.magnitude_n > primary.magnitude_n:
                primary = f
        if np.linalg.norm(total_force) < 1e-09:
            total_force = np.asarray(primary.normalized()) * primary.magnitude_n
            notes.append('opposing forces cancelled; solved for the dominant force only')
        load_face = canonical_face(primary.face)
        if load_face in constrained:
            load_face = opposite_face(load_face)
            notes.append(f'load face {primary.face} is held by the fixture; load applied on {load_face} instead')
        return (constraint_faces, load_face, total_force)

    def analyze_mesh(self, vertices: np.ndarray, triangles: np.ndarray, description: str='', object_id: str='obj') -> Analysis:
        t0 = time.perf_counter()
        notes: list[str] = []
        lc = self.load_case_for(description)
        grid = self._voxelize_within_budget(vertices, triangles, notes)
        constraint_faces, load_face, total_force = self._solver_faces(lc, notes)
        fem = solve_voxel_fem(grid, fixed_faces=constraint_faces, load_face=load_face, load_vector_n=total_force, young_modulus_mpa=lc.young_modulus_mpa, poisson=lc.poisson)
        plan = plan_from_stress(grid, fem.von_mises, yield_mpa=lc.yield_mpa, safety_factor=lc.safety_factor, layer_height_mm=self.layer_height_mm)
        analysis = Analysis(object_key=object_id, load_case=lc, grid=grid, fem=fem, plan=plan, wall_seconds=time.perf_counter() - t0, notes=notes)
        analysis.confidence = strength_confidence(plan, grid, fem.von_mises)
        analysis.savings = self._estimate_savings(plan, grid)
        analysis.options = build_options(grid, fem.von_mises, yield_mpa=lc.yield_mpa, safety_factor=lc.safety_factor, layer_height_mm=self.layer_height_mm, infill_density=self.infill_density)
        self.analyses[object_id] = analysis
        return analysis

    def _estimate_savings(self, plan: Plan, grid) -> dict:
        return estimate_material(plan, grid, add_perimeters=self.cfg.add_perimeters, layer_height_mm=self.layer_height_mm or 0.2, enable_solid_infill=self.cfg.enable_solid_infill, infill_density=self.infill_density)

    def run_offline(self, vertices, triangles, description: str, object_id: str='obj') -> Analysis:
        return self.analyze_mesh(vertices, triangles, description, object_id)

    def analysis_for(self, obj) -> Analysis | None:
        key = object_key(obj)
        analysis = self.analyses.get(key)
        if analysis is not None:
            return analysis
        mesh = get_mesh(obj)
        if mesh is None:
            log.warning('no mesh access for %s', key)
            return None
        try:
            return self.analyze_mesh(mesh[0], mesh[1], self.description, key)
        except Exception as exc:
            log.warning('analysis failed for %s: %s', key, exc)
            return None

    def apply_mutations(self, ctx) -> MutationStats:
        total = MutationStats()
        for obj in iter_print_objects(ctx):
            analysis = self.analysis_for(obj)
            if analysis is None:
                continue
            try:
                alignment = compute_alignment(obj, analysis.grid)
                total.merge(apply_plan_to_object(obj, analysis.plan, analysis.grid, self.cfg, alignment))
            except Exception as exc:
                log.warning('mutation failed on %s: %s', analysis.object_key, exc)
        return total

    def on_pos_slice(self, ctx):
        try:
            if self.capabilities is None:
                self.capabilities = probe(ctx)
                log.info('host capabilities: %s', self.capabilities.as_dict())
            if self.layer_height_mm is None:
                self.layer_height_mm = _config_float(ctx, 'layer_height')
            density = _config_float(ctx, 'sparse_infill_density')
            if density is None:
                density = _config_float(ctx, 'fill_density')
            if density is not None and 0.0 <= density <= 100.0:
                self.infill_density = density / 100.0 if density > 1.0 else density
            for obj in iter_print_objects(ctx):
                if object_key(obj) in self.analyses:
                    continue
                a = self.analysis_for(obj)
                if a is None:
                    continue
                log.info('analyzed %s in %.2fs: maxVM=%.1f MPa allow=%.1f MPa reinforced=%d relaxed=%d', a.object_key, a.wall_seconds, a.plan.max_vm_mpa, a.plan.allowable_mpa, a.plan.n_reinforced_layers, a.plan.n_relaxed_layers)
        except Exception as exc:
            log.exception('posSlice hook failed (non-fatal): %s', exc)
        return ctx

    def on_pos_prepare_infill(self, ctx):
        try:
            stats = self.apply_mutations(ctx)
            if self._last_mutation is None:
                self._last_mutation = stats
            else:
                self._last_mutation.merge(stats)
            log.info('mutations: +%d perimeters added, %d removed; %d solidified', stats.perimeters_added, stats.perimeters_removed, stats.surfaces_solidified)
        except Exception as exc:
            log.exception('posPrepareInfill hook failed (non-fatal): %s', exc)
        return ctx

    def on_gcode_postprocess(self, gcode_text: str) -> str:
        try:
            stats = self._aggregate_stats()
            stats.update(self._measured_stats(gcode_text))
            block = receipt_block(stats)
            lines = [ln for ln in gcode_text.splitlines() if not ln.startswith(';ECOSLICE')]
            insert_at = 0
            for i, ln in enumerate(lines[:50]):
                if ln.startswith(';') and 'generated' in ln.lower():
                    insert_at = i + 1
                    break
            return '\n'.join(lines[:insert_at] + block.splitlines() + lines[insert_at:])
        except Exception as exc:
            log.exception('postprocess hook failed (non-fatal): %s', exc)
            return gcode_text

    def _measured_stats(self, gcode_text: str) -> dict:
        """Filament mass and print time as the slicer itself reported them.

        Read from the export footer of the very file being post-processed, so the
        receipt can put a measured number next to its own estimate instead of
        leaving the reader to trust the model alone.
        """
        try:
            footer = parse_gcode_footer(gcode_text)
        except Exception as exc:
            log.debug('footer parse failed: %s', exc)
            return {}
        out = {}
        if footer.get('filament_g') is not None:
            out['measured_filament_g'] = footer['filament_g']
        if footer.get('print_time_s') is not None:
            out['measured_print_time_s'] = footer['print_time_s']
        return out

    def _aggregate_stats(self) -> dict:
        if not self.analyses:
            return {'mode': 'eco-slice idle (no analysis ran)'}
        keys = sorted(self.analyses)
        stats = self.analyses[keys[0]].stats(self.cfg, self._last_mutation)
        if len(keys) > 1:
            stats['objects_analyzed'] = len(keys)
        return stats

def _config_float(ctx, key: str) -> float | None:
    getter = getattr(ctx, 'config_value', None)
    if not callable(getter):
        return None
    try:
        value = getter(key)
    except Exception:
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None

def default_pipeline(description: str='', **kw) -> EcoSlicePipeline:
    return EcoSlicePipeline(description=description, **kw)

try:
    import orca
except ImportError:
    orca = None

from pathlib import Path as _AdapterPath

PLUGIN_NAME = "EcoSlice"
PLUGIN_VERSION = __version__

DEFAULT_CONFIG = {
    "description": "shelf bracket holding 8 kg, load downward; screwed to left wall",
    "option": "balanced",
    "resolution": 32,
    "add_perimeters": 2,
    "max_extra_perimeters": 4,
    "enable_solid_infill": True,
    "enable_relax": True,
    "enable_solid_downgrade": False,
}


def create_pipeline(**kwargs) -> EcoSlicePipeline:
    return EcoSlicePipeline(**kwargs)


_default_pipeline: EcoSlicePipeline | None = None


def get_pipeline() -> EcoSlicePipeline:
    global _default_pipeline
    if _default_pipeline is None:
        _default_pipeline = create_pipeline()
    return _default_pipeline


def describe() -> dict:
    return {
        "name": PLUGIN_NAME,
        "version": PLUGIN_VERSION,
        "capabilities": ["SlicingPipeline"],
        "hooks": ["posSlice", "posPrepareInfill", "psGCodePostProcess"],
        "license": "AGPL-3.0-or-later",
    }


def _apply_config(pipe: EcoSlicePipeline, cfg_json: str) -> None:
    try:
        cfg = json.loads(cfg_json or "{}")
    except Exception:
        cfg = {}
    if not isinstance(cfg, dict):
        cfg = {}
    merged = dict(DEFAULT_CONFIG)
    merged.update(cfg)
    pipe.description = str(merged.get("description", ""))
    resolution = merged.get("resolution")
    if isinstance(resolution, int) and 8 <= resolution <= 96:
        pipe.resolution = resolution
    mc = pipe.cfg
    # An option preset seeds the mutation strength; explicit keys still win over it,
    # so a user who edits a single value does not silently get the whole preset.
    preset = PRESETS_BY_KEY.get(str(merged.get("option", "")).strip().lower())
    if preset is not None:
        mc.add_perimeters = preset.add_perimeters
        mc.max_extra_perimeters = preset.max_extra_perimeters
        mc.enable_solid_infill = preset.enable_solid_infill
        mc.enable_relax = preset.enable_relax
    for key, caster in (
        ("add_perimeters", int),
        ("max_extra_perimeters", int),
        ("enable_solid_infill", bool),
        ("enable_relax", bool),
        ("enable_solid_downgrade", bool),
    ):
        if key in cfg:
            setattr(mc, key, caster(cfg[key]))


if orca is not None:

    _Step = orca.slicing.Step

    def _result(kind: str = "success", message: str = "", data: str = ""):
        try:
            if kind == "success":
                return orca.ExecutionResult.success(message, data)
            if kind == "skipped":
                return orca.ExecutionResult.skipped(message)
            return orca.ExecutionResult.failure("error", message, data)
        except AttributeError:
            return None

    class EcoSliceCapability(orca.slicing.SlicingPipelineCapabilityBase):
        """execute(ctx) is called for every pipeline step, so it dispatches on ctx.step."""

        def get_name(self) -> str:
            return PLUGIN_NAME

        def has_config_ui(self) -> bool:
            return False

        def get_default_config(self) -> dict:
            return dict(DEFAULT_CONFIG)

        def execute(self, ctx):
            step = getattr(ctx, "step", None)
            if step not in (_Step.posSlice, _Step.posPrepareInfill, _Step.psGCodePostProcess):
                return _result("skipped", "step not handled by EcoSlice")

            pipe = get_pipeline()
            try:
                _apply_config(pipe, self.get_config())
            except Exception as exc:
                log.warning("EcoSlice config unreadable (%s); using defaults", exc)

            try:
                if step == _Step.psGCodePostProcess:
                    return self._post(ctx, pipe)
                if ctx.cancelled():
                    return _result("skipped", "slicing cancelled")
                if step == _Step.posPrepareInfill:
                    pipe.on_pos_prepare_infill(ctx)
                    stats = pipe._last_mutation
                    added = stats.perimeters_added if stats else 0
                    removed = stats.perimeters_removed if stats else 0
                    return _result(
                        "success", f"EcoSlice: +{added} / -{removed} perimeter-lines"
                    )
                pipe.on_pos_slice(ctx)
                a = next(iter(pipe.analyses.values()), None)
                msg = f"EcoSlice analyzed {len(pipe.analyses)} object(s)"
                if a is not None:
                    msg += (f"; maxVM={a.plan.max_vm_mpa:.1f} MPa allow="
                            f"{a.plan.allowable_mpa:.1f} MPa reinforced={a.plan.n_reinforced_layers}")
                return _result("success", msg)
            except Exception as exc:
                return _result("failure", f"EcoSlice non-fatal error: {exc}")

        def _post(self, ctx, pipe: EcoSlicePipeline):
            path = getattr(ctx, "gcode_path", None)
            if not path:
                return _result("skipped", "no gcode_path at psGCodePostProcess")
            p = _AdapterPath(str(path))
            try:
                text = p.read_text(encoding="utf-8", errors="replace")
            except OSError as exc:
                return _result("failure", f"cannot read gcode: {exc}")
            out = pipe.on_gcode_postprocess(text)
            if out == text:
                return _result("skipped", "receipt already present")
            try:
                p.write_text(out, encoding="utf-8")
            except OSError as exc:
                return _result("failure", f"cannot write gcode: {exc}")
            return _result("success", "EcoSlice carbon receipt embedded")

    @orca.plugin
    class EcoSlicePackage(orca.base):
        def register_capabilities(self) -> None:
            orca.register_capability(EcoSliceCapability)

else:
    EcoSliceCapability = None

