from __future__ import annotations

import ast
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src" / "ecoslice"
OUT = ROOT / "plugin" / "ecoslice_core.py"

MODULE_ORDER = [
    ("__init__", "__version__"),
    ("voxelize", "voxelize"),
    ("fem", "fem"),
    ("loadcase", "loadcase"),
    ("mapping", "mapping"),
    ("host_bridge", "host_bridge"),
    ("mutate", "mutate"),
    ("receipt", "receipt"),
    ("pipeline", "pipeline"),
]

PEP723_HEADER = """# /// script
# name = "EcoSlice"
# version = "0.1.0"
# description = "Load-aware walls & infill: FEM-driven localized reinforcement inside OrcaSlicer"
# requires-python = ">=3.12"
# dependencies = [
#   "numpy>=1.26",
#   "scipy>=1.11",
# ]
# ///
# EcoSlice Core - load-aware walls & infill for OrcaSlicer.
# Copyright (C) 2026 EcoSlice contributors. License AGPL-3.0-or-later.
# This file is generated by tools/build_plugin.py - do not edit by hand.
"""

ADAPTER = '''

try:
    import orca
except ImportError:
    orca = None

import json as _adapter_json
from pathlib import Path as _AdapterPath

PLUGIN_NAME = "EcoSlice"
PLUGIN_VERSION = __version__


def create_pipeline(**kwargs) -> EcoSlicePipeline:
    return EcoSlicePipeline(**kwargs)


_default_pipeline: EcoSlicePipeline | None = None


def get_pipeline() -> EcoSlicePipeline:
    global _default_pipeline
    if _default_pipeline is None:
        _default_pipeline = create_pipeline()
    return _default_pipeline


def describe() -> dict:
    return {
        "name": PLUGIN_NAME,
        "version": PLUGIN_VERSION,
        "capabilities": ["SlicingPipeline"],
        "hooks": ["posSlice", "posPrepareInfill", "psGCodePostProcess"],
        "license": "AGPL-3.0-or-later",
    }


DEFAULT_CONFIG_JSON = (
    "{{"
    "\\"description\\": \\"shelf bracket holding 8 kg, load downward; screwed to left wall\\", "
    "\\"resolution\\": 40, "
    "\\"add_perimeters\\": 2, "
    "\\"max_extra_perimeters\\": 4, "
    "\\"enable_solid_infill\\": true, "
    "\\"enable_relax\\": true"
    "}}"
)


def _apply_config(pipe: EcoSlicePipeline, cfg_json: str) -> None:
    try:
        cfg = _adapter_json.loads(cfg_json or "{}")
    except Exception:
        cfg = {}
    pipe.description = str(cfg.get("description", pipe.description or ""))
    if isinstance(cfg.get("resolution"), int) and 8 <= cfg["resolution"] <= 96:
        pipe.resolution = int(cfg["resolution"])
    mc = pipe.cfg
    mc.add_perimeters = int(cfg.get("add_perimeters", mc.add_perimeters))
    mc.max_extra_perimeters = int(cfg.get("max_extra_perimeters", mc.max_extra_perimeters))
    mc.enable_solid_infill = bool(cfg.get("enable_solid_infill", mc.enable_solid_infill))
    mc.enable_relax = bool(cfg.get("enable_relax", mc.enable_relax))


if orca is not None:

    _Step = orca.slicing.Step

    def _result(kind: str = "success", message: str = "", data: str = ""):
        try:
            if kind == "success":
                return orca.ExecutionResult.success(message, data)
            if kind == "skipped":
                return orca.ExecutionResult.skipped(message)
            return orca.ExecutionResult.failure("error", message, data)
        except AttributeError:
            return None

    class EcoSliceCapability(orca.slicing.SlicingPipelineCapabilityBase):
        def get_name(self) -> str:
            return PLUGIN_NAME

        def has_config_ui(self) -> bool:
            return False

        def get_default_config(self) -> str:
            return DEFAULT_CONFIG_JSON

        def execute(self, ctx):
            pipe = get_pipeline()
            try:
                _apply_config(pipe, self.get_config())
            except Exception:
                pass
            try:
                step = ctx.step
                if step == _Step.psGCodePostProcess:
                    return self._post(ctx, pipe)
                if step == _Step.posPrepareInfill:
                    pipe.on_pos_prepare_infill(ctx)
                    return _result("success", "EcoSlice infill mutations applied")
                pipe.on_pos_slice(ctx)
                a = pipe.analyses.get("obj0")
                msg = f"EcoSlice analyzed {len(pipe.analyses)} object(s)"
                if a is not None:
                    msg += (f"; maxVM={a.plan.max_vm_mpa:.1f} MPa allow="
                            f"{a.plan.allowable_mpa:.1f} MPa reinforced={a.plan.n_reinforced_layers}")
                return _result("success", msg)
            except Exception as exc:
                return _result("failure", f"EcoSlice non-fatal error: {exc}")

        def _post(self, ctx, pipe: EcoSlicePipeline):
            path = getattr(ctx, "gcode_path", None)
            if not path:
                return _result("skipped", "no gcode_path at psGCodePostProcess")
            p = _AdapterPath(str(path))
            try:
                text = p.read_text(encoding="utf-8", errors="replace")
            except OSError as exc:
                return _result("failure", f"cannot read gcode: {exc}")
            stats = pipe._aggregate_stats()
            mutation = getattr(pipe, "_last_mutation", None)
            if mutation is not None:
                for k, v in {
                    "perimeters_added": mutation.perimeters_added,
                    "perimeters_removed": mutation.perimeters_removed,
                }.items():
                    stats.setdefault(k, v)
            out = pipe.on_gcode_postprocess(text)
            p.write_text(out, encoding="utf-8")
            return _result("success", "EcoSlice carbon receipt embedded")

else:
    EcoSliceCapability = None


if orca is not None:

    @orca.plugin
    class EcoSlicePackage(orca.base):
        def register_capabilities(self) -> None:
            orca.register_capability(EcoSliceCapability)

'''


def strip_local_imports(tree: ast.Module, local_names: set[str]) -> tuple[ast.Module, list[str]]:
    keep = []
    binds: list[str] = []
    for node in tree.body:
        if isinstance(node, ast.ImportFrom) and node.module == "__future__":
            continue
        if isinstance(node, ast.ImportFrom):
            mod = (node.module or "").split(".")[0]
            local = node.level > 0 or mod in local_names
            if local:
                for a in node.names:
                    if a.name == "*":
                        continue
                    if a.asname:
                        binds.append(f"{a.asname} = {a.name}")
                continue
            node.names = [a for a in node.names if a.name.split(".")[0] not in local_names]
            if not node.names:
                continue
        elif isinstance(node, ast.Import):
            kept = [a for a in node.names if a.name.split(".")[0] not in local_names]
            for a in node.names:
                if a.name.split(".")[0] in local_names and a.asname:
                    binds.append(f"{a.asname} = {a.name.split('.')[-1]}")
            node.names = kept
            if not node.names:
                continue
        keep.append(node)
    return ast.Module(body=keep, type_ignores=[]), binds


def main() -> int:
    local_names = {label for _, label in MODULE_ORDER} | {"ecoslice"}
    parts = [PEP723_HEADER, "\nfrom __future__ import annotations\n"]
    for mod, label in MODULE_ORDER:
        path = SRC / f"{mod}.py"
        if not path.exists():
            print(f"missing module: {path}", file=sys.stderr)
            return 1
        source = path.read_text(encoding="utf-8")
        tree = ast.parse(source)
        tree, binds = strip_local_imports(tree, local_names)
        body = ast.unparse(tree)
        if binds:
            body += "\n" + "\n".join(binds)
        parts.append(f"\n\n# {'=' * 70}\n# module: {label}\n# {'=' * 70}\n{body}")
    parts.append(ADAPTER)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("".join(parts), encoding="utf-8")
    compile(OUT.read_text(encoding="utf-8"), str(OUT), "exec")
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
