from __future__ import annotations

import ast
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src" / "ecoslice"
OUT = ROOT / "plugin" / "ecoslice_core.py"

MODULE_ORDER = [
    ("__init__", "__version__"),
    ("voxelize", "voxelize"),
    ("fem", "fem"),
    ("loadcase", "loadcase"),
    ("mapping", "mapping"),
    ("host_bridge", "host_bridge"),
    ("mutate", "mutate"),
    ("receipt", "receipt"),
    ("options", "options"),
    ("pipeline", "pipeline"),
]

PEP723_HEADER = """# /// script
# requires-python = ">=3.12"
# dependencies = [
#   "numpy>=1.26",
#   "scipy>=1.11",
# ]
#
# [tool.orcaslicer.plugin]
# name = "EcoSlice"
# version = "0.1.0"
# description = "Load-aware walls & infill: FEM-driven localized reinforcement inside OrcaSlicer"
# author = "EcoSlice contributors"
# ///
# EcoSlice Core - load-aware walls & infill for OrcaSlicer.
# Copyright (C) 2026 EcoSlice contributors. License AGPL-3.0-or-later.
# This file is generated by tools/build_plugin.py - do not edit by hand.
"""

ADAPTER = '''

try:
    import orca
except ImportError:
    orca = None

from pathlib import Path as _AdapterPath

PLUGIN_NAME = "EcoSlice"
PLUGIN_VERSION = __version__

DEFAULT_CONFIG = {
    "description": "shelf bracket holding 8 kg, load downward; screwed to left wall",
    "option": "balanced",
    "resolution": 32,
    "add_perimeters": 2,
    "max_extra_perimeters": 4,
    "enable_solid_infill": True,
    "enable_relax": True,
    "enable_solid_downgrade": False,
}


def create_pipeline(**kwargs) -> EcoSlicePipeline:
    return EcoSlicePipeline(**kwargs)


_default_pipeline: EcoSlicePipeline | None = None


def get_pipeline() -> EcoSlicePipeline:
    global _default_pipeline
    if _default_pipeline is None:
        _default_pipeline = create_pipeline()
    return _default_pipeline


def describe() -> dict:
    return {
        "name": PLUGIN_NAME,
        "version": PLUGIN_VERSION,
        "capabilities": ["SlicingPipeline"],
        "hooks": ["posSlice", "posPrepareInfill", "psGCodePostProcess"],
        "license": "AGPL-3.0-or-later",
    }


def _apply_config(pipe: EcoSlicePipeline, cfg_json: str) -> None:
    try:
        cfg = json.loads(cfg_json or "{}")
    except Exception:
        cfg = {}
    if not isinstance(cfg, dict):
        cfg = {}
    merged = dict(DEFAULT_CONFIG)
    merged.update(cfg)
    pipe.description = str(merged.get("description", ""))
    resolution = merged.get("resolution")
    if isinstance(resolution, int) and 8 <= resolution <= 96:
        pipe.resolution = resolution
    mc = pipe.cfg
    # An option preset seeds the mutation strength; explicit keys still win over it,
    # so a user who edits a single value does not silently get the whole preset.
    preset = PRESETS_BY_KEY.get(str(merged.get("option", "")).strip().lower())
    if preset is not None:
        mc.add_perimeters = preset.add_perimeters
        mc.max_extra_perimeters = preset.max_extra_perimeters
        mc.enable_solid_infill = preset.enable_solid_infill
        mc.enable_relax = preset.enable_relax
    for key, caster in (
        ("add_perimeters", int),
        ("max_extra_perimeters", int),
        ("enable_solid_infill", bool),
        ("enable_relax", bool),
        ("enable_solid_downgrade", bool),
    ):
        if key in cfg:
            setattr(mc, key, caster(cfg[key]))


if orca is not None:

    _Step = orca.slicing.Step

    def _result(kind: str = "success", message: str = "", data: str = ""):
        try:
            if kind == "success":
                return orca.ExecutionResult.success(message, data)
            if kind == "skipped":
                return orca.ExecutionResult.skipped(message)
            return orca.ExecutionResult.failure("error", message, data)
        except AttributeError:
            return None

    class EcoSliceCapability(orca.slicing.SlicingPipelineCapabilityBase):
        """execute(ctx) is called for every pipeline step, so it dispatches on ctx.step."""

        def get_name(self) -> str:
            return PLUGIN_NAME

        def has_config_ui(self) -> bool:
            return False

        def get_default_config(self) -> dict:
            return dict(DEFAULT_CONFIG)

        def execute(self, ctx):
            step = getattr(ctx, "step", None)
            if step not in (_Step.posSlice, _Step.posPrepareInfill, _Step.psGCodePostProcess):
                return _result("skipped", "step not handled by EcoSlice")

            pipe = get_pipeline()
            try:
                _apply_config(pipe, self.get_config())
            except Exception as exc:
                log.warning("EcoSlice config unreadable (%s); using defaults", exc)

            try:
                if step == _Step.psGCodePostProcess:
                    return self._post(ctx, pipe)
                if ctx.cancelled():
                    return _result("skipped", "slicing cancelled")
                if step == _Step.posPrepareInfill:
                    pipe.on_pos_prepare_infill(ctx)
                    stats = pipe._last_mutation
                    added = stats.perimeters_added if stats else 0
                    removed = stats.perimeters_removed if stats else 0
                    return _result(
                        "success", f"EcoSlice: +{added} / -{removed} perimeter-lines"
                    )
                pipe.on_pos_slice(ctx)
                a = next(iter(pipe.analyses.values()), None)
                msg = f"EcoSlice analyzed {len(pipe.analyses)} object(s)"
                if a is not None:
                    msg += (f"; maxVM={a.plan.max_vm_mpa:.1f} MPa allow="
                            f"{a.plan.allowable_mpa:.1f} MPa reinforced={a.plan.n_reinforced_layers}")
                return _result("success", msg)
            except Exception as exc:
                return _result("failure", f"EcoSlice non-fatal error: {exc}")

        def _post(self, ctx, pipe: EcoSlicePipeline):
            path = getattr(ctx, "gcode_path", None)
            if not path:
                return _result("skipped", "no gcode_path at psGCodePostProcess")
            p = _AdapterPath(str(path))
            try:
                text = p.read_text(encoding="utf-8", errors="replace")
            except OSError as exc:
                return _result("failure", f"cannot read gcode: {exc}")
            out = pipe.on_gcode_postprocess(text)
            if out == text:
                return _result("skipped", "receipt already present")
            try:
                p.write_text(out, encoding="utf-8")
            except OSError as exc:
                return _result("failure", f"cannot write gcode: {exc}")
            return _result("success", "EcoSlice carbon receipt embedded")

    @orca.plugin
    class EcoSlicePackage(orca.base):
        def register_capabilities(self) -> None:
            orca.register_capability(EcoSliceCapability)

else:
    EcoSliceCapability = None

'''


def strip_local_imports(tree: ast.Module, local_names: set[str]) -> tuple[ast.Module, list[str], list[str]]:
    """Split a module into (body, alias-rebinds, hoisted imports as (module, name, asname))."""
    keep = []
    binds: list[str] = []
    hoisted: list[str] = []
    for node in tree.body:
        if isinstance(node, ast.ImportFrom) and node.module == "__future__":
            continue
        if isinstance(node, ast.ImportFrom):
            mod = (node.module or "").split(".")[0]
            local = node.level > 0 or mod in local_names
            if local:
                for a in node.names:
                    if a.name == "*":
                        continue
                    if a.asname:
                        binds.append(f"{a.asname} = {a.name}")
                continue
            node.names = [a for a in node.names if a.name.split(".")[0] not in local_names]
            if not node.names:
                continue
            for a in node.names:
                hoisted.append((node.module, a.name, a.asname))
            continue
        elif isinstance(node, ast.Import):
            kept = [a for a in node.names if a.name.split(".")[0] not in local_names]
            for a in node.names:
                if a.name.split(".")[0] in local_names and a.asname:
                    binds.append(f"{a.asname} = {a.name.split('.')[-1]}")
            node.names = kept
            if not node.names:
                continue
            for a in node.names:
                hoisted.append((None, a.name, a.asname))
            continue
        if isinstance(node, ast.Assign) and any(
            isinstance(t, ast.Name) and t.id == "__all__" for t in node.targets
        ):
            continue
        keep.append(node)
    return ast.Module(body=keep, type_ignores=[]), binds, hoisted


def render_imports(entries: list[tuple]) -> str:
    """One deterministic import block: plain imports first, then merged from-imports."""
    plain: list[str] = []
    from_imports: dict[str, list[str]] = {}
    for module, name, asname in entries:
        rendered = name if asname is None else f"{name} as {asname}"
        if module is None:
            line = f"import {rendered}"
            if line not in plain:
                plain.append(line)
        else:
            names = from_imports.setdefault(module, [])
            if rendered not in names:
                names.append(rendered)
    lines = plain[:]
    for module, names in from_imports.items():
        lines.append(f"from {module} import {', '.join(sorted(names))}")
    return "\n".join(lines)


def main() -> int:
    local_names = {label for _, label in MODULE_ORDER} | {"ecoslice"}
    bodies = []
    imports: list[str] = []
    for mod, label in MODULE_ORDER:
        path = SRC / f"{mod}.py"
        if not path.exists():
            print(f"missing module: {path}", file=sys.stderr)
            return 1
        source = path.read_text(encoding="utf-8")
        tree = ast.parse(source)
        tree, binds, hoisted = strip_local_imports(tree, local_names)
        for entry in hoisted:
            if entry not in imports:
                imports.append(entry)
        body = ast.unparse(tree)
        if binds:
            body += "\n" + "\n".join(binds)
        bodies.append(f"\n\n# {'=' * 70}\n# module: {label}\n# {'=' * 70}\n{body}")

    parts = [PEP723_HEADER, "\nfrom __future__ import annotations\n\n"]
    parts.append(render_imports(imports) + "\n")
    parts.extend(bodies)
    parts.append(ADAPTER)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("".join(parts), encoding="utf-8")
    compile(OUT.read_text(encoding="utf-8"), str(OUT), "exec")
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
